### ISSUE TITLE
Fix portuguese translation.

### ISSUE THREAD

**Issue by LucasAlfare** [cs0x7f/cstimer#10]
I saw some elements not translated yet, however, some which are translated appear not in UFT-8 (chars like Ç are making some grammar errors).

**Comment by cs0x7f** [comment]
Well, I cannot speak Portuguese and have no idea how to deal with this. Could you please send the correct translation to me?

**Comment by LucasAlfare** [comment]
That's ok for me then. Just teach me how to send it for you.

**Comment by cs0x7f** [comment]
Well, you can download and modify  https://github.com/cs0x7f/cstimer/blob/master/src/lang/pt.js  to the correct version, and send to my email: cs0x7f@gmail.com

**Comment by LucasAlfare** [comment]
Allright, that's fine. But another thing, I can't see in the file the About, Introduction, Statistics, etc texts, because it stills in english yet.

**Comment by LucasAlfare** [comment]
of course @superluminosity , thank you!
