### ISSUE TITLE
Timer display shifted up and hidden by scramble 

### ISSUE THREAD

**Issue by tussosedan** [cs0x7f/cstimer#100]
Happens on Android, on /new and /src too

![Screenshot_20190905-191633_Chrome](https://user-images.githubusercontent.com/32999689/64360061-5674e180-d012-11e9-83c0-8968a8fb8450.jpg)

**Comment by cs0x7f** [comment]
Is it fixed after this commit: https://github.com/cs0x7f/cstimer/commit/2a461aca07590d0cf5c1bc2731f4b2b41d2be021

**Comment by tussosedan** [comment]
Seems to work well on /src!

**Comment by cs0x7f** [comment]
> 
> 
> Seems to work well on /src!

/new, / and /src should be the same right now (or due to browser cache problem). The cache strategy of /src is different from /new . In /src, no offline cache is enabled for convenience of debugging (so it's impossible to use /src offline)

**Comment by tussosedan** [comment]
Yup, I refreshed my PWA and it works well now. Thanks!
