### ISSUE TITLE
Locking phone gives inaccurate timings

### ISSUE THREAD

**Issue by prendradjaja** [cs0x7f/cstimer#101]
Hello! I've got csTimer installed as a PWA (added to my home screen), and I noticed that if I lock my phone, leave it for a few minutes, and then unlock, the timer shows something like 30 seconds.

**Comment by jscheidtmann** [comment]
Which OS? What phone? Which version of csTimer?

**Comment by prendradjaja** [comment]
Hello!

OS: Android 10
Phone: Essential Phone PH-1
csTimer version: 2019.09.15

Just tried this again and I should add that it doesn't require waiting a few minutes -- I waited about one minute and found that the timer ended up at about 30 seconds.
