### ISSUE TITLE
Button for copy scramble to clipboard

### ISSUE THREAD

**Issue by andersonaap** [cs0x7f/cstimer#103]
I often share scrambles in whatsapp and paste in Google Keep;
It would be helpful a button for copy the scramble to clipboard 
or Share Button;

**Comment by andersonaap** [comment]
Can label it as 'Feature Request' or 'Enhancement'

**Comment by cs0x7f** [comment]
I cannot find a universal solution to copy something to clipboard. Although there are some clipboard features in html5, the copy-to-clipboard ability is not implemented in most of modern browsers.

**Comment by andersonaap** [comment]
https://clipboardjs.com/
https://www.w3schools.com/howto/tryit.asp?filename=tryhow_js_copy_clipboard

I tested both samples on windows IE11, Chrome, Firefox and Edge. 
(I can imagine that works on Safari).
Problably works on instaled PWA on Android.

**Comment by andersonaap** [comment]
Now I see: https://caniuse.com/#feat=mdn-api_document_execcommand_copy
is deprecated.

**Comment by cs0x7f** [comment]
Implemented in https://github.com/cs0x7f/cstimer/commit/48b224297798e98e29bd030e69eb842925dc83cd
I didn't add a new button, the copy action can be triggered by clicking the scramble instead (not available by default).

**Comment by andersonaap** [comment]
Hi

I tested https://cstimer.net/new/
Its OK (chrome, firefox, ie11, edge, chrome and installed on android).

Thanks :)

**Comment by topppits** [comment]
Could you add this to the "Solves No.xxx" window as well, so we can easily copy the scramble of an older solve as well?

This here: https://i.imgur.com/3nNPoEr.png

Clicking on the part that's outlined blue in the picture to copy a scramble would be awesome.

This is a bit OT, but clicking on the time I just realised, that it's a bit inconsistent. When you click on any time in your "summary" (your PBs) you get the "Current Round Statistics" pop-up. Same goes for the times in the time list on the right - e.g. ao5, ao12, whatever you choose for that. But when you click on the time in the timelist, you get the "Solves No.xxx" window. To get the "Current Round Statistics" for a single solve from your time list, you need to click on the number on the left.

Not sure if you should change it, just feels like inconsistent behaviour.

**Comment by cs0x7f** [comment]
Updated in https://github.com/cs0x7f/cstimer/commit/2fc7eb22b958c5d2fe395d793cd302cb002727ad
Does it meet your expectations?

**Comment by topppits** [comment]
Oh man, this is perfect! Much better than what I proposed, I love it <3

There's a bug, when clicking on +2 or DNF, the solve time changes to Nan.Nan+. After that happened, clicking OK/+2/DNF doesn't change anything for this solve. Using the shortcuts ctrl+1/2/3 works fine and when you clicked +2 or DNF for the most recent solve, you can change it back with the shortcuts, but no way to do that for older solves.

**Comment by cs0x7f** [comment]
Fixed in https://github.com/cs0x7f/cstimer/commit/edcb9632b32f1bb2a0a17d9d09c391999fba3b8e
