### ISSUE TITLE
The states of GAN356i and virtual cube are not synced

### ISSUE THREAD

**Issue by bestmove68gin** [cs0x7f/cstimer#106]
When I used a previous version of csTimer, GAN356i worked fine...

Below is a screen shot when I connect GAN356i and just do single U move.
![gan356i_issue](https://user-images.githubusercontent.com/56713145/69898457-3cdb0000-139d-11ea-82d0-a208232687eb.png)

**Comment by cs0x7f** [comment]
Does it occur when you turn the cube slowly, e.g. tps less than 4?

**Comment by bestmove68gin** [comment]
Yes. Regardless of turning speed, this strange pattern appears. 
(I have also GiiKER i3S and it works perfectly.)

> Does it occur when you turn the cube slowly, e.g. tps less than 4?

**Comment by cs0x7f** [comment]
Fixed. Refresh the page and try again.
It's due to an unexpected code removal in a previous commit.

**Comment by bestmove68gin** [comment]
Now it works perfectly! Thank you for your quick fix 😊
