### ISSUE TITLE
Random state scramble for 15 puzzle

### ISSUE THREAD

**Issue by bestmove68gin** [cs0x7f/cstimer#107]
For 15 puzzle, I feel random move scrambler made kind of poor scramble occasionally.
So I'd prefer to random state scramble like qqTimer and Slidysim.

**Comment by cs0x7f** [comment]
Implemented in https://github.com/cs0x7f/cstimer/commit/982aebf7b95e791eec5beef0abff69f7b01ddbf9
Available in https://cstimer.net/new/

**Comment by bestmove68gin** [comment]
It seems to work well! Thank you for your great improvements 😎
