### ISSUE TITLE
Scramble display for 15 puzzle

### ISSUE THREAD

**Issue by bestmove68gin** [cs0x7f/cstimer#108]
For some hardware of 15 puzzle (e.g. QiYi 15 Puzzle Magnetic Klotski), just put out pieces and place them is easier than applying a scramble sequence.
So, I'd like to add scramble drawer or, to be enough, just show the position of the pieces as a scramble string (like Slidysim).

For example,
```
+--+--+--+--+
|10| 2|11| 4|
+--+--+--+--+
| 5|12| 3| 7|
+--+--+--+--+
| 1| 6| 8|15|
+--+--+--+--+
| 9|13|  |14|
+--+--+--+--+
```
Above scramble will expressed as:
`10 2 11 4/5 12 3 7/1 6 8 15/9 13 0 14`

**Comment by cs0x7f** [comment]
Implemented in https://github.com/cs0x7f/cstimer/commit/982aebf7b95e791eec5beef0abff69f7b01ddbf9
Available in https://cstimer.net/new/

**Comment by bestmove68gin** [comment]
How pretty! I'm very satisfied with it 😆
