### ISSUE TITLE
How to connect 356i with cstimer

### ISSUE THREAD

**Issue by ciwomuli** [cs0x7f/cstimer#112]
I can't use cstimer to connect my 356i.I can use cube station to connect my 356i,but I can't find it through my Chrome.The bluetooth can connect other device easily.

我的356i连不上cstimer。在计时里选魔方以后chrome显示找不到任何兼容设备。魔方已经开启，手机可以正常连接，电脑也可以正常连接其他蓝牙设备。

**Comment by cs0x7f** [comment]
你需要确保
1. 356i没有和手机连上
2. 不停的摇356i（因为浏览器的蓝牙搜索通常比较慢，有的时候需要好几分钟）。
还不行的话打开：
chrome://bluetooth-internals/#devices
点右上角的start scan，看看能不能在列出的蓝牙设备里找到Gan开头的设备。找不到的话可能是电脑蓝牙不支持356i。
