### ISSUE TITLE
Virtual Cube Clean-Up

### ISSUE THREAD

**Issue by Lukas-Batema** [cs0x7f/cstimer#113]
I would like (and probably many more) would like the virtual cube to have the keys bound to the actual face notation. For example the current front face would be bound to (F), with (F’) being bound to the keyboard key of [G]. To avoid any issues with this, keep the keyboard layout connected to the language set, because there are some different language keyboards. Like in Chinese (sorry if I misspelled that), would have the front face bound to the closest letter translation to the English (UK) alphabet letter. This would solve a lot of confusion. I am still thinking of a way to be able to add this feature to other cube types. I think there should be able to have customizable virtual cube key mapping. So, if you wanted the front face to be bound to the key [V], for example, have that be able to be an option for almost all keys on a keyboard. To make sure this wouldn’t clash with shortcuts in any way, when the user creates a new key bound for a face, try implementing the shift or tab keys into the shortcut, in addition to alt or command (when Apple keyboard shortcuts get some love). Thanks!

**Comment by cs0x7f** [comment]
Make the keys bound to the actual face notation doesn't make any sense. 
The current keyboard mapping is designed for speedsolving such that muscle memory for a physical cube is available for virtual cube.
For example, on a physical cube, U is usually turned by the index finger of right hand, U' is usually turned by the index finger of left hand. Therefore, U is mapped to 'J' key and U' is mapped to 'F' key.

**Comment by Lukas-Batema** [comment]
Okay, Thanks!

**Comment by Lukas-Batema** [comment]
Maybe add touch support though for tablets and phones.

**Comment by Lukas-Batema** [comment]
I see now. I put coloured stickers on my keyboard, and it makes sense. Thanks. I’ll go ahead and close this issue!
