### ISSUE TITLE
Joke Scramble Description

### ISSUE THREAD

**Issue by Lukas-Batema** [cs0x7f/cstimer#114]
I think, when people click on the cstimer button, after getting to the bottom, there should be a description of each joke scramble. The sentence after the descriptions should be “I hope nobody tries to scramble with these scramble features, but if you do, try the 3x3x3 for noobs.” What that sentence is intended to mean, is that the user is a noob for using the joke scramble, and the writer is suggesting for the now “noob” user to use a joke scramble for noobs. Perfect, right? Thanks! 

(P.S. I hope i am not bugging y’all with all these ideas, but oh well!)

**Comment by cs0x7f** [comment]
It's just for fun.
