### ISSUE TITLE
3x3 ft still in 3x3>3x3ft

### ISSUE THREAD

**Issue by Lukas-Batema** [cs0x7f/cstimer#116]
Feet has been removed by the WCA, could you fix this, or make a new sub header in the scramble tab, called, Removed WCA Events, or be called Historic WCA Events, thanks!

**Comment by cs0x7f** [comment]
3x3x3 means that 3x3x3 cube is a WCA puzzle. Most of items in it is not WCA events (e.g. F2L, OLL, PLL)
