### ISSUE TITLE
Alg Creation Feature Idea

### ISSUE THREAD

**Issue by Lukas-Batema** [cs0x7f/cstimer#117]
I think _cstimer.net/timer.php_ should have a scramble type, that is not really a scramble, but it does almost exactly what _alg.cubing.net_ does. That means, we should be able to create and save as many of our created, unique algs that we want. That would be a pretty good feature.

**Comment by cs0x7f** [comment]
alg.cubing.net is not a website that create and save algs. Do you mean algdb.net?

**Comment by Lukas-Batema** [comment]
Yes, but be able to see the moves on the cube like on alg.cubing.net

          -Lukas Batema

**Comment by Lukas-Batema** [comment]
Dear @cs0x7f,
May I have an update on this feature request? Thank you!
