### ISSUE TITLE
Export button

### ISSUE THREAD

**Issue by Yvo3008** [cs0x7f/cstimer#12]
When you click on the export button usually there is coming a little screen where you can save your times and import them. but i doesn't work anymore, for me at least. I hope you can fix it!

**Comment by cs0x7f** [comment]
It works for me. Which browser do you use? And would you please open the console (usually press F12 in Firefox or Chrome) and check whether there is any error log(s)?

**Comment by Yvo3008** [comment]
Hey,

I normally use Chrome but I had Firefox on my computer so i tried it with
Firefox and it works there, so its fine for me now.
Thank you for responding that quickly btw.
And sorry for my bad English in some sentences (i'm Dutch)

Bye

2017-12-23 15:10 GMT+01:00 Chen Shuang <notifications@github.com>:
