### ISSUE TITLE
Export to Google server - constantly getting logged out

### ISSUE THREAD

**Issue by topppits** [cs0x7f/cstimer#122]
Very often I have to login into google again, before I can do the backup. Clicking on the export button throws me an error message, that I have to be logged in - although it looked like I was logged in. After logging in, everything works fine.

**Comment by cs0x7f** [comment]
Due to some security policies of google's service, the login status might be out of date after several hours or several days.
csTimer do not check whether the token of google is out of date or not. So when it shows you are logged in, the login status might have already been out of date.

**Comment by Lukas-Batema** [comment]
I also just get an error code when clicking to sign into google.

**Comment by cs0x7f** [comment]
> I also just get an error code when clicking to sign into google.
> ![07BB857C-3C0B-4FEF-BA1D-FF70294A28A2](https://user-images.githubusercontent.com/55695493/73542602-10764b00-4403-11ea-97b8-9c8d358300d0.jpeg)

Fixed.

**Comment by Lukas-Batema** [comment]
Thanks
