### ISSUE TITLE
Gan 365 iPlay DNF during CMLL

### ISSUE THREAD

**Issue by Tebro** [cs0x7f/cstimer#123]
I am using the new Gan 365 iPlay and quite often cstimer declares my time DNF. I have it configured for Roux, and it marks P3 as DNF, but it only does it when I finish the cube. 

[Example](https://alg.cubing.net/?alg=D%2F*0*%2F%20R%2F*437*%2F%20U%27%2F*811*%2F%20F%27%2F*1953*%2F%20B%2F*1960*%2F%20R%27%2F*2603*%2F%20F%27%2F*3011*%2F%20B%2F*3020*%2F%20F%27%2F*3113*%2F%20B%2F*3130*%2F%20D%27%2F*3842*%2F%20F%2F*5049*%2F%20F%2F*5651*%2F%20L%27%2F*5938*%2F%20B%27%2F*7987*%2F%20F%2F*7999*%2F%20R%2F*8625*%2F%20U%2F*10028*%2F%20F%2F*10490*%2F%20F%2F*10864*%2F%20F%2F*12282*%2F%20U%27%2F*12656*%2F%20F%27%2F*12777*%2F%20U%27%2F*13448*%2F%20F%27%2F*13636*%2F%20B%2F*13650*%2F%20F%27%2F*14042*%2F%20B%2F*14051*%2F%20D%2F*14455*%2F%20D%2F*14573*%2F%20F%2F*14818*%2F%20D%27%2F*14953*%2F%20F%27%2F*15064*%2F%20F%27%2F*17212*%2F%20D%2F*17608*%2F%20F%2F*17806*%2F%20B%27%2F*18328*%2F%20F%2F*18361*%2F%20L%27%2F*18521*%2F%20F%27%2F*18761*%2F%20B%2F*18777*%2F%20F%27%2F*18873*%2F%20B%2F*18897*%2F%20B%27%2F*19387*%2F%20D%27%2F*19734*%2F%20B%2F*19758*%2F%20R%27%2F*21688*%2F%20U%2F*23492*%2F%20F%2F*23877*%2F%20R%27%2F*23913*%2F%20F%27%2F*23983*%2F%20R%27%2F*24189*%2F%20F%2F*24429*%2F%20F%27%2F*24754*%2F%20R%2F*24760*%2F%20U%27%2F*24964*%2F%20R%2F*26833*%2F%20R%2F*27044*%2F%20F%2F*27522*%2F%20R%2F*27574*%2F%20F%27%2F*27608*%2F%20U%27%2F*27794*%2F%20F%2F*28080*%2F%20R%2F*28138*%2F%20F%27%2F*28176*%2F%20R%27%2F*28350*%2F%20F%27%2F*28435*%2F%20U%2F*28578*%2F%20F%2F*28726*%2F%20F%2F*28821*%2F%20R%27%2F*28850*%2F%20F%27%2F*28958*%2F%20F%27%2F*29933*%2F%20B%2F*29951*%2F%20U%2F*31041*%2F%20B%27%2F*31329*%2F%20F%2F*31347*%2F%20R%2F*31471*%2F%20F%27%2F*31608*%2F%20B%2F*31623*%2F%20B%27%2F*33256*%2F%20F%2F*33279*%2F%20R%2F*33484*%2F%20R%2F*33555*%2F%20F%27%2F*33815*%2F%20B%2F*33826*%2F%20U%2F*34355*%2F%20F%27%2F*34472*%2F%20B%2F*34485*%2F%20F%27%2F*34550*%2F%20B%2F*34565*%2F%20D%27%2F*35540*%2F%20U@%26%2345%3B283488%20&setup=R%20U%20F%27%20B%27%20R%20F%20L2%20D%27%20F%27%20R2%20U%20F2%20L2%20D2%20L2%20B2%20D%27%20R2%20F2)

**Comment by cs0x7f** [comment]
I don't have a 356i Play. So I'm not able to reproduce the bug right now.
