### ISSUE TITLE
No inspection when using Stackmat

### ISSUE THREAD

**Issue by Lukas-Batema** [cs0x7f/cstimer#124]
Is there a way for there to be inspection for Stackmat solves?

**Comment by topppits** [comment]
Space still works, just like in your normal solves.

For some of the Speedstacks Stackmat timer you can also touch your right sensor shortly and it'll trigger inspection time. I think you need to tick "Use Stackmat Status Information" under option -> timer. Still it's a hit or miss if it'll actually work with your timer.

**Comment by Lukas-Batema** [comment]
Mobile I mean.

**Comment by topppits** [comment]
So, I guess you mean your input type is typing and you use a stackmat timer without it being connected to the device on which you run cstimer, right? Or are you actually in stackmat mode and connected to a mobile device that recognises the stackmat timer?

If it's the first case, I'm not sure how useful it'd be. Cstimer would have no way of knowing if you already started execution and it would also have no way of telling if you exceed the 15/17 seconds inspection time. So it'd be a timer that counts from 0 to 15 (or opposite) with sound/visual indications at 8 and 12 seconds, if you want that. Though those indications could be disruptive if you started your solve already.

If it's the second scenario, it'd certainly be nice to have a trigger button to start inspection time on mobile, though I doubt there are many people out there who actually have a working setup like that.

So what exactly would you like to have?

**Comment by Lukas-Batema** [comment]
I was really thinking of the second scenario. That is great!

**Comment by Lukas-Batema** [comment]
@topppits May I have an update on this issue as well? Thank you!

Best Wishes,
          Lukas Batema

**Comment by topppits** [comment]
Hi @Lukas-Batema, I'm not a dev here at all. I was just trying to help precise what exactly it is you're requesting.

@cs0x7f seems to be busy again with work. When he last pushed all of those new features out I think he just finished studying and was looking for a job or sth. along those lines. So if there isn't anyone else who's interested in implementing new features into cstimer themselves we probably have to wait until @cs0x7f has time and motivation again.

**Comment by Lukas-Batema** [comment]
Dear @topppits,
Thank you for the information!
Best Wishes,
Lukas Batema
