### ISSUE TITLE
Draw scramble cut

### ISSUE THREAD

**Issue by PierreSC2** [cs0x7f/cstimer#127]
Hello !
On my computer, the scramble drawing is cut on the bottom. But on the phone, it is right.
I hope it can be fixed
Thanks for all
Pierre

**Comment by bugybunny** [comment]
A screenshot would help a lot how it looks on your computer.

**Comment by PierreSC2** [comment]
I solved the problem : Draw scramble size
But I kept the previous size (20) and it hasn't any problem. Now it's 17
But I just had to scroll down to see the full draw. I'll send later a screenshot
