### ISSUE TITLE
Random state 15 puzzle scrambles contain cancelling moves

### ISSUE THREAD

**Issue by benwh1** [cs0x7f/cstimer#128]
e.g.

D2 R U L D R U2 L D R D L U R2 U R D L2 U R2 D L3 U R D2 **R U2 D2 R** D L3 U R3 U L D L U R2 U L2 D3 **L U D R3**

Things like R R can also appear in scrambles. This probably comes from the solutions of the three phases being concatenated

**Comment by cs0x7f** [comment]
It has been fixed in /new/
