### ISSUE TITLE
Session changing problem

### ISSUE THREAD

**Issue by bdo6612** [cs0x7f/cstimer#132]
I cant change a session on phone. On cpmputer obly usinh keyboard shortucut
![Screenshot_20200412-173041_Chrome](https://user-images.githubusercontent.com/63551188/79072843-93f5c780-7ce3-11ea-94fd-67abbb0d2f38.jpg)

**Comment by tussosedan** [comment]
Oh, I'm not the dev but I think I actually know what happened. It can't be seen on a black background, but there's a quarter circle thingy you can hit right here to make it show up:

![image](https://user-images.githubusercontent.com/32999689/79694475-13057580-8279-11ea-9dc1-be5c18857bd2.png)
