### ISSUE TITLE
Can't enter into native cstimer app while offline

### ISSUE THREAD

**Issue by eXil3d** [cs0x7f/cstimer#134]
For 1 or 2 days, I am facing a new problem in my cstimer android. I can't enter into the cstime application while I am offline. It says, "Can't connect it this site(https://photos.app.goo.gl/vMDSM3HJGVvUWPvg6) ". I don't use any smart cube. Also it is taking much more time to load than before.  
My version is 2019.12.24

**Comment by iseexsd** [comment]
This isn't a problem with cstimer. The "app" you are speaking of is just a self-contained link to the website. You can't connect to a website without being online.

**Comment by tussosedan** [comment]
@iseexsd not quite, one of the features of [PWA](https://en.wikipedia.org/wiki/Progressive_web_application) is working offline.
