### ISSUE TITLE
I pressed import and lost 210 times please help

### ISSUE THREAD

**Issue by TheAnnoyingCuber** [cs0x7f/cstimer#144]

**Comment by topppits** [comment]
That is way too little information to help you.

**Comment by TheAnnoyingCuber** [comment]
On cstimer in the very left but in the right I pressed the button and then pressed import from server (Google) and pressed OK and deleted my solves.

**Comment by topppits** [comment]
Okay, what I got so far from you:

- You previously backed up your times. (probably)
- you imported that/a backup
- Now you've lost 210 times. 

Where were those 210 times? Were they not backed up? Should they have been in the backup? Did you do solves after you backed up the last time and imported an old session? Seriously, you're giving so little information that nobody can seriously even attempt to help you. I still don't really know what your problem even is. Describe EXACTLY what happened or I'm out.
