### ISSUE TITLE
Feature request: topXX Solve Tools for a session and Rank

### ISSUE THREAD

**Issue by BrainTwists** [cs0x7f/cstimer#145]
I think it would be very useful to have a "Best Times"  chunk available in the Tools section.  Taking the full session list and having it resort with fastest time first.  Would be good to have options of "Top 12", "Top 50", or "All" to view the best times of a session.

It could also take all the mo3 or ao5  (I guess any aoX) and have those also displayed Best First.

**Comment by cs0x7f** [comment]
Now we are able to sort the time list by single/ao5/ao12. Since ao5 and ao12 are configurable, you can show best of any aoX/moX.
