### ISSUE TITLE
avg of 100 is wrong

### ISSUE THREAD

**Issue by winiel559** [cs0x7f/cstimer#149]
Hello, here is one of my session

best single: 9.62
worst single: 20.99
mean of 100: 13.33
avg of 100: 13.20

total time of 100 = 13.33*100 = 1333
1333 - best single - worst single = 1302.39
correct avg of 100 = 1302.39/98 = 13.29 
which is different from what csTimer gave me (13.20)
ao5 ao12 were correct, though.

BTW, I'd like to see ao50 since I can't play 4x4 or above for >=100 solves.

```
於2020-06-26使用csTimer計時
完成/總計: 100/100

最佳單次
    最佳: 9.62
    最差: 20.99

3 次平均
    本次: 14.07 (σ = 3.06)
    最佳: 11.32 (σ = 1.61)

5 次去頭尾平均
    本次: 13.16 (σ = 1.53)
    最佳: 11.80 (σ = 0.44)

12 次去頭尾平均
    本次: 13.77 (σ = 1.17)
    最佳: 12.49 (σ = 1.03)

100 次去頭尾平均
    本次: 13.20 (σ = 1.26)
    最佳: 13.20 (σ = 1.26)

去頭尾平均:13.20(標準差=1.26)
平均:13.33
```

**Comment by winiel559** [comment]
here's the exported csv [https://mega.nz/file/18NkQQ5Z#KuN8WZo-TzAVhfmnY2UeL5S0GMm5RMeUAXKzZOWJCtI](url)

**Comment by bugybunny** [comment]
I would have guessed that csTimer removes the fastest 10 and slowest 10 percent (which is also the number of solves for an Ao100) of the solves. Or was it 5%? 
I’m not sure if there is a general consensus as to what should be removed for bigger averages.

**Comment by topppits** [comment]
What @bugybunny said - the fastest and slowest 5%, rounded up, are being removed. That's the case for all averages. For ao5 and ao12, 5% rounded up simply equals 1. For ao50 it's 2.5 -> rounded up = 3.

cstimer actually added an option to change that to your liking under option -> statistics -> number of solves trimmed at each side:

Though in general when cubers talk about an average, it's 5% each, rounded up.

**Comment by winiel559** [comment]
I've found the settings, thanks for clarifying!

**Comment by TheBasketballFan79** [comment]
> What @bugybunny said - the fastest and slowest 5%, rounded up, are being removed. That's the case for all averages. For ao5 and ao12, 5% rounded up simply equals 1. For ao50 it's 2.5 -> rounded up = 3.
> 
> cstimer actually added an option to change that to your liking under option -> statistics -> number of solves trimmed at each side:
> 
> Though in general when cubers talk about an average, it's 5% each, rounded up.

Oh... I use 10 percent
