### ISSUE TITLE
Exporting sessions

### ISSUE THREAD

**Issue by mzfr** [cs0x7f/cstimer#15]
In what all format can we export sessions ? 
I can only export the sessions in txt format and I can't see any other option there. But after seeing [this](https://github.com/cs0x7f/cstimer/pull/6) it seems that I am missing something.

**Comment by cs0x7f** [comment]
When you click on one of ao5/ao12 cells or the session solve/average cell in the time list, a dialog titled "Current Session Statistics" or "Current Session Statistics" will be popped up. There are two buttons at the bottom of the dialog. Click "export CSV" and you will get a csv file which can be opened by Microsoft excel.

**Comment by mzfr** [comment]
@cs0x7f Thanks a lot :+1:
