### ISSUE TITLE
Feature Request: Show highest streak sub-X solves

### ISSUE THREAD

**Issue by eff96** [cs0x7f/cstimer#152]
e.g.:

<10: [123](https://www.youtube.com/watch?v=dQw4w9WgXcQ) you click the link and it shows you the times.
<9: [12](https://www.youtube.com/watch?v=dQw4w9WgXcQ) and the scramble
<8: [3](https://www.youtube.com/watch?v=dQw4w9WgXcQ) you get the idea

**Comment by cs0x7f** [comment]
Now we are able to show solves sorted by its time/ao5/ao12.
