### ISSUE TITLE
Feature Request: Megaminx PLL Trainer

### ISSUE THREAD

**Issue by eff96** [cs0x7f/cstimer#153]
i'm currently learning full PLL for megaminx an some cases are nearly impossible to distinguish from one another, especially the Q and X cases.
i wish there was a trainer for PLL so i can learn these cases easier.
if someone knows any trainer for megaPLL, then please tell me, it would be greatly appreciated.

**Comment by eff96** [comment]
ok i found [this](https://nogesma.github.io/Megaminx-PLL-Trainer/) but it only contains cases that are mostly easy to recognise, it doesnt contain the 'no bars' cases like L and X. ill be using this for now though.

**Comment by eff96** [comment]
nvm the link above has all the algs now

**Comment by cs0x7f** [comment]
Implememted by an optimal solver in <R U R', F' U F, U>
