### ISSUE TITLE
Time distribution not so clear

### ISSUE THREAD

**Issue by jcSoftMob** [cs0x7f/cstimer#155]
From the tools detail page:

> Time distribution and stability analysis, > X Y/Z means there are totally Y solves less than X seconds, and all of the latest Z solves are less than X seconds in the session.

time distribution in FireFox 77.0.1 (64bit) on Ubuntu 14.04 is shown like this:
15+	2	 <16	**1**/2
16+	4	 <17	1/6
17+	11	 <18	1/17
18+	11	 <19	1/28
19+	11	 <20	1/39
20+	5	 <21	1/44
21+	6	 <22	**6**/50
22+	4	 <23	6/54
23+	5	 <24	6/59
24+	3	 <25	6/62
**<X-1>+  Y    <X       ?/Z?** ...whatsoever...

Not so clear for me... i'm missing the meaning of the digit(s) before the "/".
Maybe the Tools Detail page needs a refresh...
Thanx

**Comment by rwuwon** [comment]
**?** denotes the current sub-Z streak.

Time distribution is explained under **_csTimer/ABOUT > Tools detail > time distribution_**:
> "Time distribution and stability analysis, <X Y/Z means there are totally Y solves less than X seconds, and all of the latest Z solves are less than X seconds in the session."

Using a few lines from your example:

> 19+ 11 <20 1/39

In this session you have 11 solves between 19 and 20 seconds, and 39 solves that are sub-20. The 1/39 - specifically the 1/ means you have a current streak of 1 solve that is sub-20.

> 20+ 5 <21 1/44

44 sub-21 solves, with a current streak of 1 sub-21.

> 21+ 6 <22 6/50

The current streak is 6 solves in a row being sub-22, and 50 solves in the sesion being sub-22.
