### ISSUE TITLE
Change default number of moves for FTO scrambles from 25 to 30

### ISSUE THREAD

**Issue by KitClement** [cs0x7f/cstimer#156]
The FTO community has recently shifted from the standard of 25 to 30 move scrambles due to 25 moves not producing enough possible scrambles to match the state space of FTO. FTO has the following number of permutations:

6!/2 - corner permuation
2^5 - corner orientation
(12!/3!^4)^2 - triangle permutation
12!/2 - edge permutation
divided by 12 since orientation is not fixed by centers.

This gives about 3.14\*10^22 states. An upper bound for the number of 25 move scrambles on FTO is 16\*14^24 = 1.53\*10^28.

If using 30 move scrambles, a lower bound for the number of states is 16\*14\*12^28 = 3.69\*10^32. 

As a comparison, before random state scrambles on 3x3x3, we used 25 move scrambles. While these had issues with EO-balanced states, we know that there were [(3+√6)\*(6+√54)^25 + (3-√6)\*(6-√54)^25]/4 = 1.86\*10^28 possible scrambles, which is almost 10^9 more possible scrambles than states. The 30 move standard for FTO achieves at least this threshold, which is part of the reason for making this change. In the few months that people have been practicing FTO, people have also self-reported easier scrambles with 25 movers compared to 30 movers, but of course this can fall to confirmation bias. Given the relative size of the puzzle state space and the number of possible scrambles, a change to 30 seems potentially necessary, and has become the standard for achieving records in our community.

For this reason, we would greatly appreciate if the default number of moves changed to 30 on CSTimer rather than 25 to ensure everyone is using higher quality scrambles with CSTimer. Thanks for your time!

**Comment by jxu** [comment]
Is reaching all states sufficient? Shouldn't there be stats on simulated scrambles, ex. average piece travel distance? (Maybe there already are, I don't follow FTO)

**Comment by KitClement** [comment]
> Is reaching all states sufficient? Shouldn't there be stats on simulated scrambles, ex. average piece travel distance? (Maybe there already are, I don't follow FTO)

Yes, absolutely, I just haven't done any analysis of this yet. Also, I have known for a while that the math I did was wrong, your reply inspired me to correct it just now!
