### ISSUE TITLE
Keyboard shortcut for 'typing' time input using Firefox

### ISSUE THREAD

**Issue by edladd84** [cs0x7f/cstimer#163]
According to the documentation, ctrl-alt-i should switch the timer input method to typing.  It doesn't seem to be working for me, but the other shortcuts do work (like v for virtual and t for timer).

Cheers,
Ed

**Comment by topppits** [comment]
Works fine for me.

btw which documentation are you referring to?

**Comment by edladd84** [comment]
@topppits I wasn't sure where I'd found them, but perhaps unsurprisingly it was on Reddit!  lol

https://www.reddit.com/r/Cubers/wiki/cstimer#wiki_shortcuts

i is still the only shortcut that fails for me on two different computers.  Maybe it's a firefox thing?  I'll check it on Chrome.

**Comment by edladd84** [comment]
Yeah - it works on Chrome, but not on Firefox.

**Comment by topppits** [comment]
ah yeah, I wrote that wiki article - it's by no means anything official! But those shortcuts should work anyways. Hopefully it can be fixed on Firefox.

**Comment by roccovp3** [comment]
the shortcut works on firefox for me, may be a different issue, but this one should probably be closed
