### ISSUE TITLE
No inspection voice sounds on iOS browsers though setting config on

### ISSUE THREAD

**Issue by sakabar** [cs0x7f/cstimer#166]
# Abstract
No inspection voice sounds on iOS browsers though I set inspection setting. 

# Reproduction
1. Use iOS13.6, Google Chrome 85
2. Go https://cstimer.net/
3. Set config : timer -> use WCA inspection : `Always`
4. Set config : timer -> voice alert of WCA inspection : `male voice`
5. Set config : timer -> Volume voice : `100` 
6. Turn up the volume of the iPhone
7. Unset silent mode of the iPhone
8. (Optional) Check sound : tools -> metronome -> start. It sounds.
9. Start timer and wait for 8 seconds.
10. "8s!" is shown, but no voice sounds.

# Probable cause
The iOS audio restriction. It allows to sound only when a user touched display. 

# Links
https://stackoverflow.com/questions/46363048/onaudioprocess-not-called-on-ios11/46534088#46534088
https://developers.google.com/web/updates/2017/09/autoplay-policy-changes#webaudio

**Comment by dsoegijono** [comment]
I'm running into a similar issue on macOS (11.0.1) Safari 14, but works fine on Chrome.

**Comment by jelly12315** [comment]
So it doesn’t work of safari iOS at all.. or is there a solution.
