### ISSUE TITLE
GAN 356 i sync issues

### ISSUE THREAD

**Issue by franklinvv** [cs0x7f/cstimer#168]
I have a GAN 356 i and GAN 356 i2. Both cubes experience problems during solves, where csTimer apparently does not register all moves properly, so it's no longer in sync with the physical cube. This leads to frustration because the physical cube is solved whereas csTimer shows a slightly scrambled cube. (This happens on approximately 30% to 40% of my solves.)

I have a feeling (with an emphasis on feeling) that it happens during corner cutting with moves that either do not get registered properly or in the wrong order.

Since these issues don't appear when using the GAN Cube Station app or other web based services, I do not think this is hardware related.

**Comment by HoshiYamazaki** [comment]
> I have a GAN 356 i and GAN 356 i2. Both cubes experience problems during solves, where csTimer apparently does not register all moves properly, so it's no longer in sync with the physical cube. This leads to frustration because the physical cube is solved whereas csTimer shows a slightly scrambled cube. (This happens on approximately 30% to 40% of my solves.)
> 
> I have a feeling (with an emphasis on feeling) that it happens during corner cutting with moves that either do not get registered properly or in the wrong order.
> 
> Since these issues don't appear when using the GAN Cube Station app or other web based services, I do not think this is hardware related.

It is. I bought Fenvi T919 because I wanted to have bluetooth card for my desktop and ouch, it works better than before. The same was told by speedsolving forum members.
