### ISSUE TITLE
I know that csTimer can be used on phones but it would be really cool to have a cstimer mobile app which could sync with the data on the pc without having to log in again and again to export solves. Thank you!

### ISSUE THREAD

**Issue by 1080pixelz** [cs0x7f/cstimer#173]

**Comment by Lukas-Batema** [comment]
@1080pixelz 
You can use it as a native app [here](https://github.com/cs0x7f/cstimer#using-as-native-app). Also, please check previous issues, as one has been opened a while ago on this subject. Thank you!

Best Wishes,
Lukas Batema
