### ISSUE TITLE
It reset all my solves

### ISSUE THREAD

**Issue by JECUBER** [cs0x7f/cstimer#177]
One of these days I opened the app of cs timer and when a went to look at my 3x3 session all my solves were gone. I checked other cubes session's and they were all gone

**Comment by topppits** [comment]
With that little information nobody can really help you. It's unlikely that you're getting your times back. You should try to find out why your times were deleted - maybe an app cleared your cookies or sth like that?

The main takeaway from this is:
You've learned the hard way, that worrying about backups after you've lost your data is too late.

Don't make the mistake for other, actually really important data and start backing up your stuff NOW.

I'm sorry for your loss.

**Comment by joseluisrdzrobles** [comment]
yeah i unfortunaly accidentaly deleted more than 1600+ solves on cstimer
