### ISSUE TITLE
Indicator when a Sq1 scramble leaves the cubeshape

### ISSUE THREAD

**Issue by bugybunny** [cs0x7f/cstimer#18]
Random state Square-1 scrambles seem to always stay in cubeshape for a few slices. Thus, some sort of indication when the scramble leaves the cubeshape would be helpful in my opinion to reduce the number a user misscrambles.  (btw I use cubeshape as synonym for Square/Square, the “solved” cubeshape)

The idea comes from Squanmate (https://cdn.rawgit.com/sp3ctum/squanmate/master/resources/public/index.html#/ and https://github.com/sp3ctum/squanmate/) that does this. Go to the website, select a case and then generate a new scramble. Here’s a screenshot of what it looks like.

![image](https://user-images.githubusercontent.com/5311105/38419612-71bb7886-39a1-11e8-9ce6-788764018f10.png)

The blue part indicates that after (0,-2)/ you should be out of cubeshape. Sometimes there’s an asterisk indicating that you leave the cubeshape with misaligned squares but that’s not relevant here. I would like to see something similar to this blue font color in csTimer that shows me when I have to leave the cubeshape. 

Somewhere, an explantion what this asterisk/different color (or whatever it ends up to be) represents is needed and I have no good idea how to display it. Maybe the same way like Squanmate does with a mousehover? This would be bad for mobile users though and they would be confused at first.

Special cases: Scrambles that go back into Square/Square would need a second asterisk to denote going back into cubeshape. I’ve btw created the same issue for TNoodlee and copied it almost 1:1.

**Comment by cs0x7f** [comment]
Wonderful idea. IMO, different colour might not be a appropriate solution. Instead, using a different font might be a better choice, such as using bold font for the '/' who separates the cubeshape part and the non-cubeshape part of the scramble.

**Comment by bugybunny** [comment]
Sounds better with the different font, yeah. Do you have an idea how to tell the user what the different font means?

**Comment by xsrvmy** [comment]
A different slash character can work too maybe (// instead of /), or a line break.

**Comment by dancing-jules** [comment]
I find it a bit weird that in the color example the blue color only starts with the (-3,0). It's the (0,-2) that brings it out of alignment and therefore out of cubeshape (because and 0<>-2 mod 3).

**Comment by xsrvmy** [comment]
Actually the color change should probably start on the slash

**Comment by cs0x7f** [comment]
Implemented in https://github.com/cs0x7f/cstimer/commit/f0f36b4f526408025324f0cea988cd585d2fe80f
Finally, I decided to use "///" to indicator when the puzzle leaves the cubeshape. Since "/" denotes the twist move, three "/"s have the same effect as "/" and can be easily handled by conventional scramble analyzer, e.g. scramble state image generator

**Comment by LucasAlfare** [comment]
I was thinking that the user might be able to choose whether to show or not to show the `///`. What do you think?

**Comment by cs0x7f** [comment]
Done in https://github.com/cs0x7f/cstimer/commit/345912dba4ee4373e1866cba6279c7e14f5fc496
An option is add to the scramble options of sq1, and '///' is disabled by default right now.

**Comment by bugybunny** [comment]
T

> Done in [345912d](https://github.com/cs0x7f/cstimer/commit/345912dba4ee4373e1866cba6279c7e14f5fc496)
> An option is add to the scramble options of sq1, and '///' is disabled by default right now.
That seems like the best solution, I like that. Thanks a lot :)

**Comment by bugybunny** [comment]
Has this feature been removed again? I cannot seem to find it anymore, not even in /new and I also don’t see an option to enable it.

**Comment by bugybunny** [comment]
Oh, I never noticed that gear icon before :D Thanks
