### ISSUE TITLE
Local Competition Mode - Sync Scramble Across Machines

### ISSUE THREAD

**Issue by ntonyho** [cs0x7f/cstimer#181]
Imagine a scenario where a group of people (2 or more) are using CSTimer to compete between themselves.

They want to have the same scramble.

How about having a HOST, which will set the mode (2x2x2, 3x3x3, etc) and distribute the scramble to all the CLIENTS/PARTICIPANTS. Would that be super nice feature?

How about just a nice way to sync something across 2 browsers? Something potentially possible with WebRTC?

**Comment by topppits** [comment]
There's basic version of that in the tool "Common Scramble". I haven't played around with it, so can't tell you more details.

**Comment by ntonyho** [comment]
Exactly what I want. It gives me the seed for the sequence of scramble
