### ISSUE TITLE
Feature Request: eX-Mars Cube Support

### ISSUE THREAD

**Issue by Lukas-Batema** [cs0x7f/cstimer#186]
Dear cs0x7f,
          I don’t know if this is even possible, but it would be nice if there could be support for the eX-Mars Cube. I really don’t know how this would work, but I am willing to help test it, as I have one of the eX-Mars Cubes. Thank you!

Best Wishes,
          Lukas Batema

**Comment by cs0x7f** [comment]
Has anyone else succeeded?
