### ISSUE TITLE
write box too big 

### ISSUE THREAD

**Issue by twothirdshuman** [cs0x7f/cstimer#192]
sometimes the box where you write your time after a solve is too big and gets outside the timer area.

this happens when i go into full screen in my browser.

specs:
firefox 86.0
ubuntu 20.04 (was able too recreate on windows)

pictures of the problem:
![Skärmbild från 2021-03-02 16-45-41](https://user-images.githubusercontent.com/75085645/109673974-d1bb4300-7b76-11eb-89a4-1a11e85febc3.png)
![Skärmbild från 2021-03-02 16-45-54](https://user-images.githubusercontent.com/75085645/109673982-d3850680-7b76-11eb-928f-6c4f831cded1.png)

**Comment by y-arjun-y** [comment]
Facing the same issue here on Chrome, macOS.
