### ISSUE TITLE
Wrong average calculation

### ISSUE THREAD

**Issue by marklau123** [cs0x7f/cstimer#196]
The average shown on the left hand side dashboard is wrong, making many of my averages DNFs.
![2021-04-28 (18)](https://user-images.githubusercontent.com/83325084/116340706-2fd07380-a812-11eb-8b33-8a78ad6a5c78.png)

**Comment by topppits** [comment]
What exactly is wrong about it?

Without further information (e.g. export of your times in that session) nobody will really be able to help you.

Certainly looks weird. The best 5% and worst 5% (rounded up) will be removed from an average. If you have more DNFs than that, your average will be a DNF. For your ao5000 to be a DNF, you'd need to have 251+ DNFs in the last 5000 solves.

I just remembered writing all this down, that there's an option where you can define how many solves should be trimmed (as I wrote above, usually that's 5%). Sounds likely to me that you've changed this option.

Go to "option" -> "statistics" -> "Number of solves trimmed at each side:" and change that to 5%

**Comment by marklau123** [comment]
I checked and it turns out that I really changed the setting! Thanks! 從 Windows 10 的郵件傳送 寄件者: topppits傳送時間: 2021年4月28日 19:16收件者: cs0x7f/cstimer副本: marklau123; Author主旨: Re: [cs0x7f/cstimer] Wrong average calculation (#196) What exactly is wrong about it?Without further information (e.g. export of your times in that session) nobody will really be able to help you.Certainly looks weird. The best 5% and worst 5% (rounded up) will be removed from an average. If you have more DNFs than that, your average will be a DNF. For your ao5000 to be a DNF, you'd need to have 251+ DNFs in the last 5000 solves.I just remembered writing all this down, that there's an option where you can define how many solves should be trimmed (as I wrote above, usually that's 5%). Sounds likely to me that you've changed this option.Go to "option" -> "statistics" -> "Number of solves trimmed at each side:" and change that to 5%—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by marklau123** [comment]
I checked and turns out I really changed the setting! Thanks!
