### ISSUE TITLE
BUG: Accidentally triggerd start and duplicated scores recorded.

### ISSUE THREAD

**Issue by Satanepigone** [cs0x7f/cstimer#197]
## Enviroment: 
- System: Windows 10 Home 20H2 19042.985
- Timer: Speed Stacks G4 connected through mic plug.
- Browser: Google Chrome 90.0.4430.212 64-bit

## Issue:
1. Start the timer and stop; now there is a time on the G4, and the same time on the cstimer; say 34.789s (not specific time, just for example).
2. Do not clear/reset the G4, keep it as is for a while.
3. Sometimes the cstimer would has the numbers/time flashed to green and flash back to the 34.789s. Now there is a new score, as 34.789s, recorded. 
4. If you still keep not touching anything, this might happen again and again, resulting in many same scores recorded.

![8UF6@ $N(J3 SGYV5SI{9}S](https://user-images.githubusercontent.com/31991677/118410348-f8a8f180-b65c-11eb-9821-ebad799d3d0e.jpg)

![Q5`2SY~%%FN1EV6@ )ZWHD1](https://user-images.githubusercontent.com/31991677/118410376-24c47280-b65d-11eb-8a5d-a6f366f8b300.jpg)
![image](https://user-images.githubusercontent.com/31991677/118410528-dbc0ee00-b65d-11eb-8061-7fa9c5dd66fb.png)

(Examples are shown above)

---------------------------
p.s.: cstimer would not record anything if the G4 is reseted to 0.000s; but it sometimes would still flash to green and then flash back.

**Comment by bestmove68gin** [comment]
I encountered this issue too!
When I use csTimer with Firefox 89.0, it seems to work properly.
I guess this is a Chrome-specific issue.
