### ISSUE TITLE
[Suggestion] Adding a square-1 CSP (cube shape parity) trainer

### ISSUE THREAD

**Issue by LucasAlfare** [cs0x7f/cstimer#20]
CSP is a technique in square-1 to solve the cube without parity problem.

One thing that can help in this is get scrambles in a fixed case or list of cases because, once when we learn one is bored wait for the case randomly (one chance in 3678 values).

Thinking in this I have been used sq12phase java classes to generating these fixed cube shapes (once I'm not familiar with javascript). I just created this gist to expose my code, using, as base, your sq12phase:

https://gist.github.com/LucasAlfare/0a3089b60c908ac6147336445641f247

Now in relation to the interface can be tought some ways to make user able to choose their cube shapes, like comboBoxes with a sided button to add that value to "_UserShapes_" list. This is just a approach.

Beyond this, another tool related to CSP can be a Parity Checker, to user checks if the result is _odd_ or _even_. This should take in mind the two inspections methods for CSP: **BLD** and **Cale** Tracing. In case of implementing _Cale Tracing Checker_, this tool should do the user click in the scramble preview (in the pieces) and get the triads and result.

If you have any questions about the CSP feel free to ask.

**Comment by cs0x7f** [comment]
Hi Lucas,
I tried to merge your implementation, and now it works in https://github.com/cs0x7f/cstimer/commit/9c20ee8ddf1a078b4d292e11788e3c8817052d4d
Since I'm not an expert on SQ1, I have some question about the CSP technique.
Firstly, I found all 3678 shapes are classified into 90 different cases. However, I notice that some shapes occur twice while some other shapes are missed. Is there any mistake?
Secondly, in current implementation, I listed all 90 cases and make them configurable (click the gear beside the scramble-type selector, same as zbll and pll for 3x3x3 cube). Should these 90 cases be further classified for convenience into less cases, e.g. no more than 30 cases?

**Comment by cs0x7f** [comment]
For example, in https://github.com/cs0x7f/cstimer/commit/9c20ee8ddf1a078b4d292e11788e3c8817052d4d#diff-ba6f265ae89234f2950c8556e8aeaa87R775 this line, shape 633, 647, 668, 674, 864, 878, 899, 905, 2267, 2281, 2302, 2308, 3240, 3254, 3275, 3281 occur twice. And some of shapes are missed.

**Comment by LucasAlfare** [comment]
Hummm... Well, when I generated these indexes I:

- used a enum object which contains info about all cubeshapes;
- generated a randomState in each value of the main shape indexes array [ShapeIdx ](https://github.com/cs0x7f/sq12phase/blob/master/Shape.java#L12);
- iterated over enum values and checked what indexes matches to current enum value and added to a list, comparing FullCube info to params of the enum object.

Is possible that in this operation some indexes could be taked twice, then I really think they can be refactored to only one, once the same index will brings the same random state cube.

**Comment by cs0x7f** [comment]
Well, I tried to fixed it for you, as shown in https://github.com/cs0x7f/cstimer/commit/6645e1be5a71e4cc14086f3596ae906ff0a8d2a2.
According to my understanding, two shapes are the same CSP case if and only if they can convert each other by a combination of top moves, bottom moves or rotations (can be represented by /(6, 6)/ for convenience).
Based on such understanding, I enumerate all possible top moves, bottom moves and rotations to verify whether each set is correct and which shape should be add to a set. And finally I obtained the final results in the commit.

**Comment by LucasAlfare** [comment]
Nice! It is working well!

Now, In the next updates, you can work to implement the spinners approach to improve user shapes selection. Something like that should be a better way to choose the cases.

Another question, the labels you used to show the cases names in the setup panel was took [scpfilter](https://github.com/cs0x7f/cstimer/blob/master/src/js/scramblers/scramble_sq1_new.js#L789) array? If yes, could it be refactored to other strings instead var names?

**Comment by cs0x7f** [comment]
Yes, it can be configured right now.

**Comment by cs0x7f** [comment]
I tried a two-level selector in https://github.com/cs0x7f/cstimer/commit/583bfccb49e060224faa841fdad558c6951f1d9b
The 90 cases are grouped according to their names, and users are able to enable/disable the whole group with one click.

**Comment by LucasAlfare** [comment]
Great implementation! But is it ready to test in `/new` version? I could not acess the update here.

**Comment by cs0x7f** [comment]
Yes, it has been released not only in /new/ but also in /
You can see something like:
`x222 3/3 |All|None|[+]
x33 3/3 |All|None|[+]
x321 3/3 |All|None|[+]
x312 3/3 |All|None|[+]
L42 3/3 |All|None|[+]
R42 3/3 |All|None|[+]`
instead of all 90 shapes in scramble options.

**Comment by LucasAlfare** [comment]
I have been checked the new version now. I liked that GUI, however I'm was wondering if is a good way organize the cases like that.

For example, if the user needs to practice only all SCALLOP cases he should to select all groups such as all SHIELD cases to be possible got a SCALLOP/SHIELD, e.g. Then doing this the user can obtain a scramble for SHIELD_KITE, e.g..

When I organized the indexes I made two enumerations: one wich contains the indexes in a concise form (reduced itens: contains all indexes for the same and for the inverted in same field) and another wich contains two elements, such as SCALLOP_SHIELD and SHIELD_SCALLOP, wich contains same indexes of the first one, to try to get a better way to give the selectors to the user.

What do you think about organizating the cases in that way?

**Comment by cs0x7f** [comment]
Well, I'm not familiar with CSP at all. It is just according to your implementation and classified according to variable names you supplied.
Is there any introduction about the CSP, how they are named and classified, and how you train it?

**Comment by LucasAlfare** [comment]
Not much material such 3x3 stuff, but you can take a look at these:

- [Icons and commons names of the shapes (scroll page down)](http://www.cubezone.be/square1step1.html);
- [Quick introduction about CSP (using BLD tracing)](http://brandonlin.com/cubing/csp.html);
- [List of all CSPs](http://hem.bredband.net/_zlv_/rubiks/sq1/sq1-csp.html);
- Optional: [Video tutorial for CSP using Cale's tracing method](https://www.youtube.com/watch?v=BLVZlRQMbSU).

### Some explanation and examples

As you saw, CSP make us solve square-1 without parity then the main idea is:

1. check if the cube is in a "even" or "odd" state during inspection;
2. solve the **cubeshape** step using a "even" or "odd" algorithm, acording to result of the inspection.

Then, in CSP, we always need to know **two fixed** ways to solve the same cubeshape: one to solve a even state and another to solve a odd state.

A way to practice CSP is to repeat the same cubeshape case(s) until memorize it (wich made the idea for generating fixed cubeshapes through the scrambles).

In this situation, when we took a case to practice we have to practice it in its **standard** and its **inverted**:

- `Standard` is a main orientation for this cubeshape, such as `X_Y`*;
- `Inverted` is the same above, but in the format `Y_X`*.

_*Obs.: `X` and `Y` is any shape for a single face, and the left letter is top and right letter is bottom._

In some CSP cases, the way to solve a `X_Y` case is different from a `Y_X` (something like mirrored algorithms), for this reason is important consider either `X_Y` and `Y_X`. E.g.: solving `Left 4-2`/`Paired edges` is different of solving `Paired edges`/`Left 4-2`.

Considering the [Icons and commons names of the shapes (scroll page down)](http://www.cubezone.be/square1step1.html) we can have that various combinations resulting in 90 different cubeshapes at all, but this value don't consider the inverted cubeshapes (`Y_X`). For example, if we have a `Shield` on the top and a `Square` at the bottom we have the same cubeshape inverted, in this case a `Square` on top and a `Shield` on bottom.

_Obs.: There are cubeshapes wich contains the same single shape in each face, such as `Scallop`/`Scallop`, `Kite`/`Kite`, `Shield`/`Shield`, etc. Cubeshapes like that doesn't have `inverteds`._

In the [List of all CSPs](http://hem.bredband.net/_zlv_/rubiks/sq1/sq1-csp.html) you can see that have 10 cubeshape cases with a `Square` shape at the bottom (note that this set contains a case for a `Kite`/`Square` inside square set). In the next set are listed the `Kite` cases, but if you count will get only 9, because there are not a "`Square/Kite`" case, once its `X_Y` is already listed above. This is a "concise way" to group all the cases. 

The full way should be, e.g.:

- All cases that contains `square`;
- All cases that contains `kite`;
- All cases that contains `barrel`;
- And so on without excluding a `inverted` on next set.

Then grouping cases in this way is best for a GUI selection, because it favors a better selection of whole groups. 

Currently if we need to train whole, e.g., Shield set we have to expand other groups to select the inverteds.

In implementation words the difference should be that we will have two fields for the same indexes, for example, this [SQUARE_KITE](https://github.com/cs0x7f/cstimer/blob/master/src/js/scramble/scramble_sq1_new.js#L724) field contains both `Square`/`Kite` and `Kite`/`Square` indexes. I think we can add a new field [here](https://github.com/cs0x7f/cstimer/blob/master/src/js/scramble/scramble_sq1_new.js#L743) called `KITE_SQUARE`, to holds the same indexes, but that will help in GUI build working to a inverted cubeshape.

If you don't understand this approach so good I can try implement these new fields in my fork and send it for you.

**Comment by cs0x7f** [comment]
Finally, I decide to classify csp cases according to https://docs.google.com/spreadsheets/d/1SvFjP5UiiJYJ4Wls341NmP_PKEd2skFyMXHm6Qsk2go/edit#gid=1709680982, which is suggested by a friend of mine

**Comment by bugybunny** [comment]
Yay, my document is useful for something
