### ISSUE TITLE
timer instantly stopping at 0.001 seconds

### ISSUE THREAD

**Issue by fluffyfloyd232** [cs0x7f/cstimer#200]
I've always had this issue on cs timer, it may be keyboard related however I feel as though this could be a simple fix i.e. not allowing 0.01 seconds solves to happen and instead just continue the timer, the exact issue I have is that I start inspection, hold down spacebar and the moment I release spacebar the timer instantly stops on 0.001 seconds. this doesn't always happen however it does happen about 1/3 solves making this website extremely difficult to use. I have looked online and I don't see other people having this same issue however if it could be solved that would be greatly appreciated as this is the only issue I have with cs timer

**Comment by SadCuber** [comment]
I use laptop and it happens in my extra keyboard.
I just time once in my laptop built-in keyboard an then try on my external keyboard then it fixes.
