### ISSUE TITLE
add speed stacking timer or just normal stopwatch

### ISSUE THREAD

**Issue by Jaketic** [cs0x7f/cstimer#204]
can there be an option for no scramble for things like speed stacking

**Comment by topppits** [comment]
In the left top corner you have the csTimer logo and 6 buttons. The button on the top right shows a 3x3 and on mouse-over it reads scramble. Click it and the scramble is gone and there will be no scramble saved with the time.

**Comment by Jaketic** [comment]
ahh thank you :)
