### ISSUE TITLE
Sessions Problem In cstimer

### ISSUE THREAD

**Issue by Greninja5** [cs0x7f/cstimer#207]
Theres some kind of problem in my cstimer where I cant see the session button therefore making me unable to switch between my sessions but when I import my data, the solves count are still intact.
How do I fix this?

![2021-07-30 (2)](https://user-images.githubusercontent.com/88210390/127702626-4ff7ecbf-8bc0-4e1d-9c5a-5f74e28b5953.png)

**Comment by lambodhar17** [comment]
I have the same issue, idk what to do
