### ISSUE TITLE
Is cstimer abandoned?

### ISSUE THREAD

**Issue by Flowkap** [cs0x7f/cstimer#208]
I recognized issues piling up as well as some PRs. 

The repo owner wasn't active on Github for a long time (at all, not only this repo). Is there anyone taking this over? 

It's an awesome project! It would be a pity if it's silently dying. 

I did not find any actively progressing fork as well.

**Comment by ZBLL-CUBER** [comment]
Well, my issue took ~20 hours to be resolved - I assume it's not abandoned!

**Comment by topppits** [comment]
Nope, it wasn't implemented just now, the feature has been there all along.

Just to make sure - I'm not the dev. I just informed you about the feature and where to find it.

**Comment by ZBLL-CUBER** [comment]
> Nope, it wasn't implemented just now, the feature has been there all along.
> 
> Just to make sure - I'm not the dev. I just informed you about the feature and where to find it.

I know that, but the fact that the issue is resolved still stands

**Comment by TheBasketballFan79** [comment]
Yeah, it's most likely abandoned.....
