### ISSUE TITLE
4x4x4 <R,r,U,u> scramble drawer draws a 3x3x3

### ISSUE THREAD

**Issue by loovjo** [cs0x7f/cstimer#21]
Pretty much self-explanatory. The attached screenshot shows the issue

![screen shot](https://user-images.githubusercontent.com/8290983/44279545-12ba0900-a252-11e8-8d94-86a709d516d3.png)

**Comment by cs0x7f** [comment]
Fixed in https://github.com/cs0x7f/cstimer/commit/bab3a12f77a10dcc354fad9842dee7d2cdee240a
