### ISSUE TITLE
Feature Request - Combine Sessions

### ISSUE THREAD

**Issue by ZBLL-CUBER** [cs0x7f/cstimer#211]
I'd love a feature that allows you to combine several sessions. I just imported each of my solves from Twisty Timer, and then realized that I have 5 other 333 sessions. So now I want to combine them in 1 big session to keep track of statistics and flex with the number of solves :D Would that be possible? I don't think that's a complex code.

**Comment by topppits** [comment]
That feature is already there. Be sure to backup your data before proceeding.

- Click on "Session" to open the Session Manager.
- In the column "Name" click on the session you want other sessions to be merged to the end to (-> choose your oldest session). The session will be marked by an asterisk next to the name.
- Now find the session you want to merge to the end of above's session and click on the three dots on the far right of the Session Manager and choose merge.
- Now you'll get a pop-up that will tell you which session will be merged to the end of which session. Make sure that you did it right and confirm.

**Comment by ZBLL-CUBER** [comment]
Thank you! I managed to do it. Love this timer :D
