### ISSUE TITLE
Whole site resetted after an update

### ISSUE THREAD

**Issue by Kinguru15** [cs0x7f/cstimer#214]
Hi! When the new update came, all of my solves and sessions disappeared and the whole website resetted. I had all of my pbs and solves there. Is there anything you guys can do, I have tried to import the times back but I never had them saved anywhere?

**Comment by Cube-Of-All-Aces** [comment]
The same thing just happened to me and I have no idea what's causing it. My guess would be to send this issue to the person who created csTimer.net

**Comment by topppits** [comment]
> When the new update came

What kind of update are you talking about?

> Is there anything you guys can do

If you have not done any Backup whatsoever, there's usually nothing anyone could do. I'm sorry for your loss.

Now think about all the other data you have (e.g. pictures you took) and start backing them up so you don't lose something really important next time.


> My guess would be to send this issue to the person who created csTimer.net

This is their github, so if they don't read it here, they probably won't read it. Also I'm not sure if they can do anything about it. The Backup tools are there for a reason - you never know what your Browser might do, so be sure to backup your data. Kind of goes for all of the data that's important to you - back it up!
