### ISSUE TITLE
All times in all sessions displayed as DNF 

### ISSUE THREAD

**Issue by junnoske** [cs0x7f/cstimer#216]
All of the times in all of my sessions are recorded as DNF within the timer. This results in all the averages showing as DNF as well, across all sessions. I am unable to manually remove the DNF as well. This happened initially on my phone, then my laptop and I have no idea why, or how to fix it. 
<img width="1440" alt="Screenshot_2021-12-28_at_12 15 54_AM" src="https://user-images.githubusercontent.com/96740034/147490204-fed44242-f4f0-47ea-9d88-bf8bc362c2a3.png">

**Comment by topppits** [comment]
Any change if you disable the plugin cstimer+?

If you could upload the txt file you get from the export, it could be of help to figure out what the problem is.
