### ISSUE TITLE
Session button missing

### ISSUE THREAD

**Issue by lambodhar17** [cs0x7f/cstimer#220]
I have no idea why and how, but i was doing OH solves a few days ago, so i switched to a different session and since then the session button is missing. I've attached an snip of it below. pls help lol
![image](https://user-images.githubusercontent.com/73583314/153803809-1246ea91-c109-4814-b088-3f6ab4faa90f.png)

**Comment by topppits** [comment]
In the top left corner of the panels time list, scramble and tools you can find [a small button](https://i.imgur.com/URVrM9B.png) (dark overlay, can be hard to see if you use a dark design/background) which hides / shows the dropdown menus.
