### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by TheBasketballFan79** [cs0x7f/cstimer#221]
I have some suggestions:

- [ ] Ability to rename sessions
- [ ] On the time trend tool, another line for the mean

**Comment by topppits** [comment]
> Ability to rename sessions

Already possible. Click on Session in your timelist right next to the dropdown menu where you can choose your session. Now hit the 3 dots in the rightmost column and you have the options to create, delete, rename, combine, split sessions and export the session times to a CSV file.

**Comment by Abivarman123** [comment]
when I open cs timer it is showing my latest time instead of 0.00. it is annoying to me. can you please add a option to stop it.
