### ISSUE TITLE
DNS servers not working

### ISSUE THREAD

**Issue by EliTheperson** [cs0x7f/cstimer#226]

**Comment by bugybunny** [comment]
oh, so it's just a DNS problem that cstimer.com cadnot be reached? Does someone hade the IP so we can at least still use it?

**Comment by Jgecc** [comment]
I don't have the IP but you can use the latest version under https://cstimer.net/new/  while there is the Problem

**Comment by topppits** [comment]
There's a fork or sth on https://www.cstimer.org/ up and running.

Seems to work fine except for the Export/Import from the cstimer-server obviously. But import from file works fine!

**Comment by paulaaaao** [comment]
My cstimer is also not working. thaks a lot for the url cstimer.org it will help a lot while .net is not working

**Comment by Samuel-de-Oliveira** [comment]
It's because the owner of project is missing??

**Comment by topppits** [comment]
Issue seems to be fixed.
