### ISSUE TITLE
[suggestion]First-block solver for roux method

### ISSUE THREAD

**Issue by sparsh2** [cs0x7f/cstimer#23]
Since roux method is becoming popular, it would be good if there is a first-block solver like cross and EO-Line solver for CFOP and ZZ methods. 
My suggestion is to add a function 'Solve first-block' that shows solutions for first-block with white or yellow base(x2 y color neutrality)

**Comment by cs0x7f** [comment]
Partially implemented in https://github.com/cs0x7f/cstimer/commit/1dfb3439cd020f50549ec2cc906bd620befd4149.
