### ISSUE TITLE
Switching to a session deletes all of its contents

### ISSUE THREAD

**Issue by aradarbel10** [cs0x7f/cstimer#230]
This happened to me a little while ago, then never happened again until now.
Switching to any existing session effectively resets it. If I take a look at the session list I can see the sessions aren't empty, but clicking any of them (either in the sessions window or in the dropdown) erases all the times. Reimporting a backup also brings back the times, but I still can't see them because I can't enter the session.

Steps to reproduce:
1. open the web app.
2. create a new empty session.
3. enter some times into it.
4. change to a different session.
5. change back in, all the entered times are now gone.

**Comment by sewe2000** [comment]
I can't reproduce this issue. In my case times are still there.

**Comment by aradarbel10** [comment]
ok it's been a while and it's happening again.
I have a strong suspicion this is related to the backup size or amount of sessions, because after removing a few it's back to behaving normally. if there's a limit on save size or something like that, maybe make sure it's not exceeded and if it does promt the user. I'll try to see if I can replicate it with more sessions/solves.
