### ISSUE TITLE
My "section" button disappear

### ISSUE THREAD

**Issue by PengpengOuO** [cs0x7f/cstimer#234]
![image](https://user-images.githubusercontent.com/111451673/185195904-b1da5a1c-ea6a-4117-bb0f-447343ee6537.png)
As the image, my section button disappear that i cant choose which section to use

**Comment by topppits** [comment]
In the top left corner of the panels time list, scramble and tools you can find [a small button](https://i.imgur.com/URVrM9B.png) (dark overlay, can be hard to see if you use a dark design/background) which hides / shows the dropdown menus: 

![image](https://user-images.githubusercontent.com/45535675/185385463-69ab679b-a1d5-4e2a-9c39-ec12ea5de5bf.png)

**Comment by PengpengOuO** [comment]
Oh i fix it, TYSM <3
