### ISSUE TITLE
Saving the timestamps of solves

### ISSUE THREAD

**Issue by tussosedan** [cs0x7f/cstimer#24]
Please save the timestamps of the solves. It's incredibly useful for analysis!

**Comment by topppits** [comment]
This would be awesome! One of the very few things I miss in cstimer.

**Comment by sillyturdle** [comment]
I have to heep a seperate spreadsheet for my pb dates, so this would be extremely helpful.

**Comment by ericlovesmath** [comment]
M, Yeah would agree with most of these

**Comment by cs0x7f** [comment]
Done in https://github.com/cs0x7f/cstimer/commit/080e82998290a783d9728e1aa93e2e450c2638d7 and https://github.com/cs0x7f/cstimer/commit/253c43d6479b4e351f4a46d5d6542e4c751911ec

**Comment by tussosedan** [comment]
Works great, thanks so much!

**Comment by ericlovesmath** [comment]
Thank you!
