### ISSUE TITLE
Can't connect GAN 356i carry to csTimer

### ISSUE THREAD

**Issue by brick098** [cs0x7f/cstimer#244]
When I try to connect the GAN 356i carry to cs timer, nothing happens except it says  "connected |  ??%"  but doesn't show the actual cube, even though the setting is enabled

**Comment by ldolse** [comment]
I've tested this at cstimer.net/src, this doesn't seem to work - I get the same results as the original poster.  I see the check-ins that were made to add support - are these online at cstimer.net/src as per the readme?
