### ISSUE TITLE
Is it possible to deploy this repo to a Github Pages?

### ISSUE THREAD

**Issue by Phoenix132** [cs0x7f/cstimer#249]
The device I use most frequently is my school computer, and I also use CSTimer a lot as well. I recently picked up cubing again and tried to access cstimer.net, however it is blocked on my school computer now. Is it possible to deploy this project on a github pages or glitch.com app? If anyone can help, many thanks!

**Comment by cs0x7f** [comment]
There are many third-party deployments of cstimer, you may find them in search engines. Actually, if you do not care about hardware or network related functions, you can directly save cstimer to static html/js/css files and then deply them anywhere.
