### ISSUE TITLE
README.md Development Section

### ISSUE THREAD

**Issue by Lukas-Batema** [cs0x7f/cstimer#253]
Hello, I am planning on creating a new section later on (in a new PR) for a local development building and testing, but I would like to know what procedures @cs0x7f goes through to build and test this project locally, so I can condense it, grammar check it, and add it to the `README.md`. Thanks!

**Comment by cs0x7f** [comment]
You may run 'make local' to obtain a local html version of cstimer (only in English). Fix bugs if not succesfully executed by yourself, e.g. folder not found, command not found, etc.
