### ISSUE TITLE
EOCross solver

### ISSUE THREAD

**Issue by effperm** [cs0x7f/cstimer#254]
similar to the solve EOLine function but a cross instead of just the front and back edges
nowadays people who use the zz method use eocross instead of eoline so a solver with all axes would be useful

**Comment by cs0x7f** [comment]
Is there any analysis about eocross, for example, depth distribution or maximum number of moves?

**Comment by effperm** [comment]
there is a distribution for [fixed eocross](https://media.discordapp.net/attachments/478546377262104607/736523655231569930/Screenshot_20200417-231004_Discord.png)
so definitely fewer moves than xxcross

**Comment by cs0x7f** [comment]
Implemented in https://github.com/cs0x7f/cstimer/commit/1412b213b220af9eb697f79807f36edfcf349d66 . EOCross solutions for all 12 orientations are provided.
