### ISSUE TITLE
Automatically disable inspection time for Blind events

### ISSUE THREAD

**Issue by topppits** [cs0x7f/cstimer#26]
For blind events we don't use inspection time.
Would it be possible to deactivate inspection automatically if the scramble type is 3BLD, 4BLD, 5BLD or mbld?
Another possibility would be to safe the inspection option for each session independently, like it is with multi phase.

**Comment by cs0x7f** [comment]
Thank you for your suggestion. It's implemented in https://github.com/cs0x7f/cstimer/commit/6e6064031fbac2fcc68f163bd9b99308b12e29e5

**Comment by topppits** [comment]
Works perfect, this is awesome! No more blind solves where I realize I only started inspection time after finishing the whole solves! So excited!
