### ISSUE TITLE
missing qCube puzzles

### ISSUE THREAD

**Issue by effperm** [cs0x7f/cstimer#260]
theres actually a [megaminx](http://mzrg.com/js/qminx-v2.html) and [clock](http://mzrg.com/js/qclock-v2.html) that i think you should include with the qCube feature
oh and you dont have to use the gelatinbrain/jfly color scheme for megaminx from that site, just use mf8

**Comment by cs0x7f** [comment]
qMinx is implemented. qClock hasn't started development yet.
