### ISSUE TITLE
Incorrect recognition of PLL skip in reconstruction tool

### ISSUE THREAD

**Issue by afedotov** [cs0x7f/cstimer#263]
Just writing to remember such case, when the time comes to fix it.

Since recognition test each cube rotation to detect progress, if one get PLL skip, then last OLL move will be recorded as PLL, not OLL move, just because step before matches to finished OLL on other cube face.

Scramble: `B2 F2 L2 F2 R2 D' R2 D' R2 U' L2 U B' L D' R2 F2 D' L B2 R`
Raw Solution: `["D@0 B'@198 B'@273 R'@633 R'@885 F@1863 L'@1974 F'@2100 U@2319 U@2469 D@6102 R@6327 D'@6657 R'@6753 R@7164 D'@7254 D'@7536 R'@7620 R'@7761 D'@7992 R@8088 D@9654 B'@10038 D'@10152 D'@10731 B@10947 D'@11103 L'@11397 D@11487 L@11589 D@13029 L@13317 D@13653 L'@13764 D'@13899 F'@14208 D@14301 F@14391 D@14538 L@14697 D'@14763 L'@14850 D'@16491 R@16635 D@16740 R'@16881 D@17010 D@17181 R@17271 D'@17379 R'@17526 D'@17868 D'@18096 B@18246 D@18411 R@18564 D'@18636 R'@18741 B'@18909 D'@19521 L@19746 B@19908 R'@20034 B'@20118 L'@20349 B@20457 R@20631 B'@20730"]`
Generated Reconstruction: [alg.cubing.net](https://alg.cubing.net/?alg=DB2R2FL%27F%27U2%20%2F%2F%20cross%207%20move(s)%0ADRDR2D%27R%20%2F%2F%20f2l-1%206%20move(s)%0ADB%27D2BD%27L%27DL%20%2F%2F%20f2l-2%208%20move(s)%0ADLDL%27D%27F%27DFDLD%27L%27%20%2F%2F%20f2l-3%2012%20move(s)%0AD%27RDR%27D2RD%27R%27%20%2F%2F%20f2l-4%208%20move(s)%0AD2BDRD%27R%27B%27D%27LBR%27B%27L%27BR%20%2F%2F%20oll%2015%20move(s)%0AB%27%20%2F%2F%20pll%201%20move(s)%0A&setup=B2%20F2%20L2%20F2%20R2%20D%27%20R2%20D%27%20R2%20U%27%20L2%20U%20B%27%20L%20D%27%20R2%20F2%20D%27%20L%20B2%20R)

**Comment by cs0x7f** [comment]
Exactly, this is a known issue, but it's not hard to fix. An interesting question is, for the CFOP approach, do we require that the last layer is not adjustable. I remember that faz posted a few videos in the early years. When dealing with F2L, you can change the last layer with some tricks.

**Comment by cs0x7f** [comment]
For the current problem, I plan to use a simple strategy: if a step only takes 1 move, then take this move to the previous non-skip step.

**Comment by afedotov** [comment]
There is possible another case. When OLL ends up not with perfect OLL skip, but with AUF. Not sure if this will be correct to take AUF move to OLL step.

**Comment by cs0x7f** [comment]
Fixed in https://github.com/cs0x7f/cstimer/commit/a07a260f1b72fbd736aeac5e147f5d78012e3a21
