### ISSUE TITLE
Bluetooth Cube "Last Scramble" button expects original scramble

### ISSUE THREAD

**Issue by Midnight145** [cs0x7f/cstimer#269]
Using the Rubik's Connected cube, and maybe other bluetooth cubes, the last scramble button does not work properly. To my understand, which I might not, it should allow you to resolve the previous scramble, but it still expects the original scramble.

**Comment by cs0x7f** [comment]
I tested, after the button is clicked, the displayed scramble is the previous one. But when you turn the cube, the scramble is still the current one. Is this what you confused about?

**Comment by Midnight145** [comment]
Yeah, I expected when I turned, that it would follow the shown (last) scramble, not go back to the original one. I'm unsure if that's intended behavior or not.

**Comment by cs0x7f** [comment]
Fixed in https://github.com/cs0x7f/cstimer/commit/80e4acb7172be37470bf3324a7f63e775b135018
