### ISSUE TITLE
Connection problem on Windows 10: "Uncaught (in promise) DOMException: GATT operation not permitted"

### ISSUE THREAD

**Issue by OliverEwald** [cs0x7f/cstimer#275]
I have a GAN 356 i carry and had no problems at all when connecting it to the cstimer on my Win 10 laptop via the Edge browser for several days. Then, suddenly overnight, the connection was not working anymore. When I start the function "Giiker cube" and then klick on "Bluetooth: connect" the dialog window pops up and after a few seconds the GAN cube is shown as ready to pair. But then, when I start the pairing nothing happens. When I investige the web page on the browser in the "console" window I see the error message "Uncaught (in promise) DOMException: GATT operation not permitted". Also with a self-written Pythin script I was able to connect to the cube and subscripe for notifications. Also this script is not able to connect to the cube anymore. The error message I get there is "[WinError -2140864509] Permission denied". With GAN's official "CubeStation" app on my iPhone everything works fine. So, it rather seems to be a Windows problem and not a problem with the GAN cube. What could be the reason that this does not work anymore? Any ideas are highly appreciated.

**Comment by cs0x7f** [comment]
It doesn't seem to be a problem with csTimer, it may be a problem with Win10 or something wrong with your bluetooth network card. Try to see if other bluetooth devices are working (bluetooth mouse, headset, etc.)
