### ISSUE TITLE
Option to change the order of the sessions

### ISSUE THREAD

**Issue by topppits** [cs0x7f/cstimer#28]
Right now there's no way to change the session order. So for many the sessions order is pretty chaotic. I'd like to have my 4BLD and 5BLD session right beneath my 3BLD session. An option to change the order of the sessions would be awesome.

**Comment by cs0x7f** [comment]
Changing the order internally is not difficult. I'm thinking about the best interactive UI.
I have a rough plan. Currently, when you click the 'Session' label, it will tell to rename session. Instead, a session-manage dialog can be popped up in the future. Then you are able to rename/reorder or do some other staffs.

**Comment by cs0x7f** [comment]
Well, I wrote a session manager with simple functions in https://github.com/cs0x7f/cstimer/commit/e6256395a10576e42d9e5fc6690afabe4ad7e243
Up and down arrow denotes 'move up' and 'move down', writing hand symbol denotes 'rename', plus symbol denotes insert a new session after the session, 'X' means delete the session.

**Comment by topppits** [comment]
Oh my god, this is awesome! Works fine, one little bug I found:
When I use alt+arrow up/down to switch through the sessions, it's still in the original order. In the list it shows the new order.

**Comment by cs0x7f** [comment]
Fixed in https://github.com/cs0x7f/cstimer/commit/8019580d63ff2e5b8dcb039d417bb57981a06127

**Comment by topppits** [comment]
"use different bgcolor to indicate selected session"

If I use board color black (RGB <=8) I don't see any indication.

Same goes for the text at the top (single/ao5/ao12) of the toolbox time trend.
