### ISSUE TITLE
BLD memo generator

### ISSUE THREAD

**Issue by Anaritus** [cs0x7f/cstimer#281]
Learning 3-style at the moment and for that reason Im doing a lot of practice solves without memorisation. My current workflow is as follows:

- I scramble my cube
- write on paper BLD memo
- start timer
- solve according to memo
- most likely get annoyed since Ive messed up
- repeat

Would love to see memo generator added to solvers. Probably would be best/easiest to keep standard notation, but keep buffer customisation since different algorithms use different buffers.

**Comment by cs0x7f** [comment]
https://github.com/cs0x7f/cstimer/wiki/BLD-Helper
Will this feature help?

**Comment by Anaritus** [comment]
That's exactly what I need! How do I turn it on on cstimer.net?

**Comment by Anaritus** [comment]
It's in beta, I see. Thanks!
