### ISSUE TITLE
Add support for twisted/flipped Buffers

### ISSUE THREAD

**Issue by RedCatstone** [cs0x7f/cstimer#283]
![Bild_2023-05-02_220510001](https://user-images.githubusercontent.com/114140180/235773808-6993eb92-4f48-4b3c-b962-8d789d1de3ba.png)
Currently this BLD Helper supports no option to flip/twist your buffer piece, so if your Buffer is LUB instead of UBL you cannot use the tool :(
(unless I am stupid...)

Quick Suggestion:
Add support for M2 stuff: C and W swap and I and S swap if they are the 2nd letter in a pair

**Comment by cs0x7f** [comment]
I'm not a BLD solver, is there an introduction to this, I'll learn it as soon as possible.

**Comment by RedCatstone** [comment]
> I'm not a BLD solver, is there an introduction to this, I'll learn it as soon as possible.

Thats fine lol. Watching the Jperm Tutorials is always a great Introduction if you're trying to learn something new:
https://www.youtube.com/watch?v=ZZ41gWvltT8&list=PLI24ciRbl8BUXyPgDEfumkHUDh0IZaqPB


Also, after making this post i found a website that does a great job at generating the BLD letters! (https://csclub.uwaterloo.ca/~krmatthe/3x3x3.cgi) Even tho it looks very old, you can select any Buffer and there are tons of method-specific things. It would be really great if this stuff would directly get implemented into csTimer tho :)
