### ISSUE TITLE
Why doesn't my GAN Cube link respond?

### ISSUE THREAD

**Issue by Stoentag000** [cs0x7f/cstimer#286]
Yesterday I received my GAN i-carry S Cube. It was good when it was connected to CubeStation, but on my Mac, it couldn't connect to Cstimer. Cstimer showed that the Bluetooth connection was successful, but it didn't respond when it rotated.I use MacOS 13.3.1(a) and the browser is Chrome 113.0.5672.126.

**Comment by cs0x7f** [comment]
Maybe you get wrong mac address. Enable this flag and try again:
about://flags/#enable-web-bluetooth-new-permissions-backend

**Comment by Stoentag000** [comment]
Thank you.The Mac told me the wrong Mac address, and I have used my Android device to get the correct Mac address.
