### ISSUE TITLE
Feature Request: BLD Helper Buffer choose face

### ISSUE THREAD

**Issue by stevish-com** [cs0x7f/cstimer#288]
I was looking to use the BLD helper to skip the memorization part and move straight to execution for now. But apparently the corner swapping alg I use (R U' R' U' R U R' F' R U R' U' R' F R) is non-standard. It swaps the Left sticker of UBL with the Down sticker of DFR. But when I enter UBL as the buffer block, the memos are written as if it's the top sticker that's being swapped. I can't find a way to choose which sticker is the buffer sticker. Is there something I'm missing?

**Comment by cs0x7f** [comment]
I don't know much about the specifics of BLD, can you provide some examples? For example, how would you encode `B' R L2 F' D F B U2 B2 D L2 D2 F2 L2 B2 R2 D L2 D R Rw'`?

**Comment by cs0x7f** [comment]
I tried to implement a new coding logic in https://github.com/cs0x7f/cstimer/commit/952f1eebd91c3b2af9661013928c23fc04bb57ba , you can try it in the beta version ( /new/ ) to see if it is the function you want.

**Comment by stevish-com** [comment]
That's it! That's exactly what I needed, it works perfectly! You rock!
