### ISSUE TITLE
15 puzzle scrambles are still broken

### ISSUE THREAD

**Issue by benwh1** [cs0x7f/cstimer#289]
The state generator is correct now, but the solutions that the solver is generating are not correct. They do not actually solve the puzzle that was given as input, so the resulting scramble states are still not distributed uniformly.

**Comment by benwh1** [comment]
Distribution of pieces from applying 10000 scramble algorithms:

![](https://github.com/cs0x7f/cstimer/assets/32911992/fb58e288-7ee7-46a0-a46e-1ddc381c7a50)

Distribution from 10000 actual random scramble states:

![](https://github.com/cs0x7f/cstimer/assets/32911992/0ac65eec-c432-49b2-928c-dc077cd67baf)

**Comment by cs0x7f** [comment]
Fixed in https://github.com/cs0x7f/cstimer/commit/b5a5269aca0013ec842201f93a429947c3716bc1
