### ISSUE TITLE
中文翻译有错别字

### ISSUE THREAD

**Issue by wwt951** [cs0x7f/cstimer#290]
中文翻译有错别字，在【设置】—【全局】—【显示对比标签】
其中的第二个选项应该是“-红+绿” 而不是 “-红+率”
![无标题](https://github.com/cs0x7f/cstimer/assets/88965752/2fa39bab-16e9-4791-9b84-953fc770eab4)

**Comment by cs0x7f** [comment]
感谢指出，已在测试版（/new/）修复。
