### ISSUE TITLE
Manually entering . as a time enters NaN.NaN

### ISSUE THREAD

**Issue by Louis-dM** [cs0x7f/cstimer#291]
Not a super important bug to fix as the results can be easily deleted. This causes a couple of weird things (time is treated as a successful 0 second solve for statistics, and total time spent is stuck at NaN.NaN).

Done on firefox on linux if that's relevant, not tested on other platforms

**Comment by cs0x7f** [comment]
Fixed in https://github.com/cs0x7f/cstimer/commit/454fa59c9130d30bdfe5b73984d7e217a90d2ecb
