### ISSUE TITLE
Times being saved to multiple sessions

### ISSUE THREAD

**Issue by Aquarmity** [cs0x7f/cstimer#295]
I have found recently that on occasion my times will be saved to multiple sessions, causing me to have to delete many from the incorrect one. For example, about 50 3x3 and 4x4 times were saved to my 5x5 session on top of being saved to their respective sessions.

I'm not very certain what steps can be done to reproduce this issue, it seems rather random; I am using a Stackmat timer, if that helps.

**Comment by cs0x7f** [comment]
Have you opened cstimer in multiple tabs simultaneously?

**Comment by Aquarmity** [comment]
I have not. It's had the solves appear in sessions I was previously in while the tab was open, but I only have the one tab open.

Also thank you for the advice! I had no idea about session manager, I'll look into that
