### ISSUE TITLE
Some functions not working using Bluetooth GAN iCarry Cube 

### ISSUE THREAD

**Issue by newzealandpaul** [cs0x7f/cstimer#296]
My GAN iCarry cube connects fine, and the cube state is shown in the function toolbox in the bottom corner. When scrambling it detects my moves.

But I cannot display a virtual cube on the main screen, and it cannot detect when my scramble is done to start timer (I have tried every method eg. U U`, U4, R4 etc. delays etc.). The "tick" is showing next to the scramble, but any moves do not start the timer, instead they just cause the scramble to try fix what I did. 

I also does not detect when I have solved the cube. 

I am running Chrome Version 114.0.5735.198.

Thank you.

**Comment by cs0x7f** [comment]
If you just connect to the smart cube in the bluetooth tool, it can only be used to record the solving steps, and you still need to use the traditional timing method.
If you want to use the smart cube for automatical timing, you need to change the option: timer -> entering in times with "bluetooth"
