### ISSUE TITLE
Pad time with 0's in csv export

### ISSUE THREAD

**Issue by ThibautVerron** [cs0x7f/cstimer#298]
Hi,

Currently the csv exports time before one minute as e.g. 12.34 or 1.23, and times above one minute as 1:23.45.

Both excel and libreoffice fail to parse that consistently, as one looks like a decimal number and the other like a time.

On the other hand, if the former time was formatted as 0:12.34 or 0:01.23 (even 0:1.23 seems to work), the parser would have no trouble formatting it all like times.

Would you consider changing the format for csv times to 0:12.34? 
I don't think that it would risk breaking any existing tool, since they already have to support that format for times over 1 minute.

Cheers!

**Comment by cs0x7f** [comment]
Change "option -> global -> time format", which will also affect the time format in exported csv file.

Reopen the issue if the problem is still unsolved.

**Comment by ThibautVerron** [comment]
Thanks for the quick reply!

So, setting the time format to ss.XX(X) makes the csv export 83.45 instead of 1:23.45. It's not quite the same, but it does work too, most software should be able to work with that as a number.

It comes at the cost of a less readable displayed time though. Is there any way to set the option separately for exporting and displaying?
