### ISSUE TITLE
Ads cover the scramble on mobile

### ISSUE THREAD

**Issue by tussosedan** [cs0x7f/cstimer#299]
Trying to use the up arrow to move it doesn't help either, the entire UI moves up. Screenshots attached.

![Screenshot_20230708_105807_Chrome](https://github.com/cs0x7f/cstimer/assets/32999689/b4af634f-5944-4685-a2e1-56d78af78af6)

![Screenshot_20230708_105819_Chrome](https://github.com/cs0x7f/cstimer/assets/32999689/4dac7d29-5cf2-4458-a719-a9b13b966bac)

**Comment by cs0x7f** [comment]
The layout and display of ads is done automatically by Google AdSense. If it affects usage, you can simply turn it off in options ( Global -> Show advistisements ).
