### ISSUE TITLE
Please do not make line-breaks in the middle of an (x, y) pair in a square-1 scramble 

### ISSUE THREAD

**Issue by dancing-jules** [cs0x7f/cstimer#30]
Something like this often happens on my sceen: 

(0, -1) / (3, 0) / (4,
-2) / (-1, 0) / (-3, 0)

It makes reading the scramble really hard to read. Either replace the space  in (x, y) with a [non-breaking space](https://en.wikipedia.org/wiki/Non-breaking_space), or remove it altogether to get (x,y).

**Comment by cs0x7f** [comment]
After this https://github.com/cs0x7f/cstimer/commit/fd951d909d8b9fbeeb3a31f981e8ce5f47ba6da0 commit, all line-breaks in sq1 scrambles should occur only after twist moves.
