### ISSUE TITLE
Feature request: Save solving method setting for Reconstruct function

### ISSUE THREAD

**Issue by lpzzz** [cs0x7f/cstimer#302]
I'm mainly an Roux player training with the reconstruct function using a bluetooth cube.
I have to manully set the solving method to Roux so that I could properly do review.
It would be great if the setting can be saved.

**Comment by cs0x7f** [comment]
Fixed in https://github.com/cs0x7f/cstimer/commit/9e9a33ef6cf6a75a00104765044b2ec6642a075d
