### ISSUE TITLE
Import Solves from Server

### ISSUE THREAD

**Issue by CBUXTON5** [cs0x7f/cstimer#303]
When we attempted to export to server (cs Timer) the data was exported but we were unable to import from server (cs Timer).  Any help would be appreciated. 
WCAID: null
Name: Lucas Buxton

**Comment by cs0x7f** [comment]
Would you mind providing your account info by clicking the "Export Accounts" button, and send it to  cs0x7f@gmail.com ?
![image](https://github.com/cs0x7f/cstimer/assets/1259527/b3d300dc-202c-4343-8685-bfec508d0e54)
