### ISSUE TITLE
Feature Request: Ability to change the green and red ahead and behind time colors

### ISSUE THREAD

**Issue by drazil100** [cs0x7f/cstimer#305]
I have my own custom colorscheme that includes a red and green for good / bad added / deleted etc. I would love to be able to change these colors but I can't find a setting for it.

**Comment by cs0x7f** [comment]
I didn't understand what you mean, is it convenient to take a screenshot?

**Comment by drazil100** [comment]
These colors.

![image](https://github.com/cs0x7f/cstimer/assets/17794391/66d2b9d4-a45f-4425-ab4b-42e3dff8b5b7)

**Comment by cs0x7f** [comment]
Implemented in https://github.com/cs0x7f/cstimer/commit/c215ec46475ba0a0b25ed3979f3c3e6ccdc81572
