### ISSUE TITLE
Auto export function does not have google as an option

### ISSUE THREAD

**Issue by afonsofrancof** [cs0x7f/cstimer#307]
The tooltip of this functionality says it supports google export, but it's not available in the drop down menu.

**Comment by cs0x7f** [comment]
Fixed in https://github.com/cs0x7f/cstimer/commit/d351de7451020e6bb21332c380701d77b6ceb0d8

**Comment by afonsofrancof** [comment]
> Fixed in https://github.com/cs0x7f/cstimer/commit/d351de7451020e6bb21332c380701d77b6ceb0d8

Awesome, thanks for the quick fix.
