### ISSUE TITLE
Save points, #solved and #attempted for multi blind

### ISSUE THREAD

**Issue by topppits** [cs0x7f/cstimer#31]
Would it be possible to save the points, amount of solves cubes and amount of attempted cubes for multi blind and also show those in the stats together with the times, but ranked after the criteria of the wca?

**Comment by cs0x7f** [comment]
Sounds difficult. If you only want to store #solved and #attempted, comments can record them.

For ranking, as csTimer does not have a ranking function for times, do you mean that the "best time" for mbld event should be replaced by the one with highest score? Or just sort all data when shown in dialog by click session average/ao5/ao12?

**Comment by topppits** [comment]
Yeah, right now I store my #solved and #attempted in the comments, it's just a bit inconvenient to go through all the comments to find out where my last attempt with the same points was and then compare 
the times to know which is the pb.

>do you mean that the "best time" for mbld event should be replaced by the one with highest score?

Ah yeah, that's exactly what I meant. Showing for single best time the one with the highest score and if there are multiple with that score, the one with the fastest time time. Showing both the points (or even better "#solved/#attempted") and the time, that would be perfect.

Mo3, ao5 and so on aren't important for mbld, I guess. But if you manage to get that working for single, it'd probably be not that big of a problem to it for the rest as well.

I know this is probably a pretty difficult task with a pretty small user base, but I thought, maybe your beautiful mind comes up with a great solution :D

Maybe an option that is saved session independently (like multi-phase), which declares a session as multiblind. If that's the case it reads the first couple characters from each solve comment which has to start with "xx/xx" and with that and the solve time you can determine the pbs?
