### ISSUE TITLE
Feature Question!

### ISSUE THREAD

**Issue by dickeytimothy** [cs0x7f/cstimer#312]
Been using cstimer for a while, and I LOVE it. 
I especially love the target time feature that was recently put in, but just now I got this showing up:

![image](https://github.com/cs0x7f/cstimer/assets/34757173/9232782e-c64e-4eb1-b11a-ef0fb45962ad)

What is the meaning of the infinity symbol in the target time?

**Comment by cs0x7f** [comment]
It means that next solve you can break pb as long as it is not DNF
