### ISSUE TITLE
Ad covers scramble on mobile

### ISSUE THREAD

**Issue by spencerchubb** [cs0x7f/cstimer#314]
Ads cover the scramble when viewing from a mobile device

**Comment by spencerchubb** [comment]
![Screenshot_20230903_142032_Chrome](https://github.com/cs0x7f/cstimer/assets/58525483/7a25bf98-01e9-4416-93c5-f6bd9fcb51b4)

**Comment by cs0x7f** [comment]
The layout and display of ads is done automatically by Google AdSense. If it affects usage, you can simply turn it off in options ( Global -> Show advistisements ).
