### ISSUE TITLE
PLEASE READ THIS OR I CUT YOUR PP

### ISSUE THREAD

**Issue by ygtcghvkg** [cs0x7f/cstimer#315]
When i ever close cstimer tab to do some of my things, when i comeback , all i see was nothing, i lost all my solve time
Its always happen when i open Cstimer in the morning

**Comment by cs0x7f** [comment]
Currently, all data (including settings, session data, etc) are stored in user browser's storage. Therefore, all data will be lost if you clear browser cache.
