### ISSUE TITLE
Feature Request: Add Qiyi Smart Timer bluetooth functionality

### ISSUE THREAD

**Issue by HawaiiLife745** [cs0x7f/cstimer#318]

**Comment by cs0x7f** [comment]
An employee of qiyi told me that the data from qiyi timer is encrypted, and they don't want to make the timer connect with cstimer wirelessly.
Even putting aside legal issues, it is very difficult to crack an encryption scheme in a short period of time. I personally do not have such ability, I can only hope that someone in the open source community has such ability.
