### ISSUE TITLE
entering times with input with timestamp

### ISSUE THREAD

**Issue by topppits** [cs0x7f/cstimer#32]
Thx for adding multi-phase timing input, this is awesome! While playing around with it, I realised that the input is a bit buggy if you include the timestamp at the end.

Right now this:

>2:36.50=1:48.32+48.18   D2 R2 B2 U' L2 U' L2 U' F2 D U' L B2 R B' U2 B2 L2 R' B2 Rw' Uw2   @6.12.2018, 16:32:36

becomes this.

>1. 2:36.50=1:48.32+48.18   D2 R2 B2 U' L2 U' L2 U' F2 D U' L B2 R B' U2 B2 L2 R' B2 Rw' Uw2   @6.12.2018   @7.12.2018, 13:40:46 
>2. 16:32:36.00   F' R' D2 L2 B D' R2 U L' F2 B2 U R2 U' L2 U2 L2 D' L2 D'   @6.12.2018, 21:10:47

The time at the end will be added as another solve, the scramble is the current scramble displayed in the session at the top. Also for the first added solve it keeps the date (here: @6.12.2018) and adds a current timestamp (here: @7.12.2018, 13:40:46).

**Comment by cs0x7f** [comment]
Thank you for your bug report. 
It seems I must change the time format displayed to avoid these problems.

**Comment by cs0x7f** [comment]
Before data recognizing, cstimer will firstly split time by newlines or commas. 
Since it's difficult to handle time format for different locale, the only thing I'm able to do is to remove "," to avoid unexpected data splitting. https://github.com/cs0x7f/cstimer/commit/0486eb3c201e822d2767a3b57778904a796b231e

**Comment by topppits** [comment]
Awesome, this works now fine!
I just remembered something else about the input. If I take an ao5 of a blind session:

> 1. (1:26.30=47.36+38.93)   R L D2 L2 U' R' B D R2 F U2 F2 D2 R2 F' D2 L2 D2 B2 D' Uw'   @6.12.2018 16:25:48 
> 2. 2:19.99=1:36.88+43.10   F2 D L2 D' L2 F2 R2 U2 L2 U2 R F' U B2 L2 R2 U' R B2 F2 Uw'   @6.12.2018 16:27:45 
> 3. 1:42.14=1:00.96+41.18   L2 B U2 D F' U F R F' D2 B2 D2 F2 L2 F2 U B2 L2 D' F2 R2 Uw2   @6.12.2018 16:30:34 
> 4. 2:36.50=1:48.32+48.18   D2 R2 B2 U' L2 U' L2 U' F2 D U' L B2 R B' U2 B2 L2 R' B2 Rw' Uw2   @6.12.2018 16:32:36 
> 5. (DNF(1:59.85)=1:19.63+40.21)   D2 R' F L2 R2 D B2 R2 U2 L2 D U2 B2 L D' B F' U' B F2 Uw'   @6.12.2018 16:35:26

Only the times that are not in brackets will be inserted. If I take times from my sighted sessions there's no problem. No idea what's going on there. This was the case before all the updates already.

**Comment by topppits** [comment]
I just tried adding some old solves with date and it just takes my current time. I thought I might have the wrong format and took a mo3 from a cstimer, but it's the same.

When I input this:

> 1. 21.04   U' L2 B2 R2 F2 D' B2 U' L2 B2 R2 L B' R D' L2 F' D2 F   @6.12.2018 14:33:04 
> 2. 22.83   F R2 D2 B L2 F' L2 B L2 D2 U2 F' L D L' R' U2 R2 U2 B2 U   @6.12.2018 14:33:48 
> 3. 22.27   F' R2 L' U' L2 U R D F U2 B D2 R2 L2 F' U2 R2 F' D2 F'   @6.12.2018 14:42:11

I get this:

> 1. 21.04   U' L2 B2 R2 F2 D' B2 U' L2 B2 R2 L B' R D' L2 F' D2 F   @10.12.2018 10:05:54 
> 2. 22.83   F R2 D2 B L2 F' L2 B L2 D2 U2 F' L D L' R' U2 R2 U2 B2 U   @10.12.2018 10:05:52 
> 3. 22.27   F' R2 L' U' L2 U R D F U2 B D2 R2 L2 F' U2 R2 F' D2 F'   @10.12.2018 10:05:53

**Comment by cs0x7f** [comment]
Solving date import is not supported right now due to i18n of the time string.
For example, in some countries, 6.12.2018 means 6th Dec. 2018, while in some other countries, it means June. 12th 2018

**Comment by cs0x7f** [comment]
Done in https://github.com/cs0x7f/cstimer/commit/a91feba07c78dfc7b1e6d92d8c31a1aff3251a2a, at least for date format YYYY-MM-DD HH-MM-SS

**Comment by topppits** [comment]
Awesome!

1. It works as long as I have a scramble included. Is it possible to just add a time + timestamp? Else I'll just add "N/A" or whatever as scramble.
Or did I just use the wrong syntax? I tried with 3 spaces and with 6 spaces between the solve time and the timestamp.

2. You're probably aware of what I'm writing next, but for the case you are not:
Do you plan to display the timestamp as YYYY-MM-DD HH:MM:SS everywhere? I think it would be good, since it is clear for everyone. Right now it's shown a bit inconsistently, e.g. if I click on the solve number or let it show my current mo3 the statistic looks like this:

```
Generated By csTimer on 2018-12-10 (solving from 2016-05-11 12:30:00 to 2016-05-11 12:30:00)
single: 36.63

Time List:
1. 36.63   N/A   @11.5.2016 12:30:00
```

Also "copying" times from one session into another would be easier if it's shown in a way that the entering times by input function works with.

**Comment by topppits** [comment]
I see you fixed both, awesome, works just as expected <3

**Comment by topppits** [comment]
Okay, found one little last thing. Solve in brackets with a comment won't be added, e.g.:

`14. (DNF(1:49.28)=57.36+51.92[3e])   F2 L D2 L D2 F2 U2 R' B2 L2 U2 F U' B2 R D' B' U' F R F Fw' Uw'   @N/A`
`98. (1:24.53[bla])      @2018-12-10 13:17:24`

**Comment by cs0x7f** [comment]
Should fixed in https://github.com/cs0x7f/cstimer/commit/a5d870a343b7d3aae0ed3e0fbca4f3c07caec01f

**Comment by topppits** [comment]
Yes, perfect! <3
