### ISSUE TITLE
Feature Request: Add Dr, Dl, and Br moves to virtual megaminx

### ISSUE THREAD

**Issue by Ucaslayy** [cs0x7f/cstimer#321]
Key binds would be: 
DR = "S" / keycode 83
DR' = "L" / 76
DL = "C" / 67
DL' = "," / 188
BR = "W" / 87
BR' = "O" / 79

**Comment by cs0x7f** [comment]
Thank you for you suggestion. 
Would you mind explaining the reason why "W/O" are mapped to "BR/BR'" instead of "BL/BL'"?

**Comment by Ucaslayy** [comment]
BR and BR’ are the primary B moves since the vast majority of people are
righty. BL moves are also hardly used even in physical solves

**Comment by cs0x7f** [comment]
Done in https://github.com/cs0x7f/cstimer/commit/921c983da13e87a368890b5e2883aae821f515f4
