### ISSUE TITLE
[Advice] Add a tool for switching methods of enter time and toggle inpection

### ISSUE THREAD

**Issue by GhostShadow0316** [cs0x7f/cstimer#322]
because sometimes I want to use my smart cube, and sometimes I want to use my keyboard
but I have to go into the settings to switch the time entering method and inspection
I really want a tool to set it up quickly

**Comment by topppits** [comment]
At least for input type there are shortcuts.

ctrl + alt +

s = stackmat
i = manual input
t = timer
m = moyu timer
v = virtual
g = bluetooth

Not sure if there are shortcuts for the other three.

**Comment by GhostShadow0316** [comment]
thank you!
