### ISSUE TITLE
Add scrambles for corner helicopter 2x2 (code included)

### ISSUE THREAD

**Issue by GhostCuber** [cs0x7f/cstimer#324]
This is a puzzle that a few friends and I have been practicing (https://www.thecubicle.com/products/yuxin-corner-helicopter-2x2). I wrote a scrambler for it, but it's inconvenient to run it in an IDE and I would love to have it implemented in csTimer. It is written in Python and I can try to translate it if necessary, but I am not a very strong coder.

https://colab.research.google.com/drive/1lLKmcVkBVVtFFCZrzdAReOp-HdT8d67O

**Comment by cs0x7f** [comment]
Done in https://github.com/cs0x7f/cstimer/commit/29b407bf4a1116ace399da2653508d1ae9e2832c
