### ISSUE TITLE
[Suggestion] Random rotation option for 3x3 last layer

### ISSUE THREAD

**Issue by martinorav** [cs0x7f/cstimer#328]
Add a toggle, that if turned on would show a random cube rotation before/after every scramble. Would help with color neutral last layer training.

**Comment by cs0x7f** [comment]
Done in https://github.com/cs0x7f/cstimer/commit/fc5dbc2e97fa98e4117c13ffbaea1383fb56faf4.
By changing "Option -> scramble -> Color neutral", you are able to do color neutral training.
