### ISSUE TITLE
Toolbox that shows #solves of the ../day/month/year

### ISSUE THREAD

**Issue by topppits** [cs0x7f/cstimer#33]
It'd be really nice to have a quick overview on how many solves I did today (today/week/month/year) in total and how many in each session.

I imagine a toolbox could be a good way to just show all session names and the number solves and the sum of all those solves. A drop down menu to specify ../day/month/year.

Could you also add sth like last 24 hours and last 12 hours. When you'd cube past midnight the "today" option wouldn't really help.

**Comment by cs0x7f** [comment]
Recorded in https://github.com/cs0x7f/cstimer/issues/34
