### ISSUE TITLE
notes seem broken

### ISSUE THREAD

**Issue by julianollivieira** [cs0x7f/cstimer#332]
notes are not exported or imported

![image](https://github.com/cs0x7f/cstimer/assets/27634828/6a6a287c-a361-409d-8c65-5f37aa7d9b6b)

exported data: `{"session1":[[[-1,291],"D  R2 D  F2 R2 D2 B2 L2 F2 U' R2 D2 B  R  F' L2 B' D2 U' L  R2 F  ","",1702039337],[[2000,94],"B2 L  D2 F2 L2 U2 L  F2 R' U2 B2 R  D  F' L' U  B  D' R  B2 U  ","test",1702040842],[[0,130],"F' U  B2 L' U  D  L' B  R' D2 B  L2 D2 B2 D2 B  D2 B' U2 F2 L2 ","",1702040847],[[0,580],"D  B2 D2 F2 R2 U' F2 R2 U2 B2 U  R2 F  R2 D2 R' U  F' D  L2 B' ","",1702040847],[[0,953],"L2 B  D2 F2 U2 F  L2 D2 F  D2 B2 F' R' B2 L' F' D' L2 R  F' U' L  ","",1702126259]],"properties":{"sessionData":"{\"1\":{\"name\":\"box\",\"opt\":{},\"rank\":1,\"stat\":[5,1,937.5],\"date\":[1702039337,1702126259]}}","sessionN":1}}`

**Comment by cs0x7f** [comment]
I can't reproduce your problem. I imported the data you gave, and the time list is the same as your screenshot.

**Comment by afedotov** [comment]
Yep, I can confirm that solve comments are exported and imported.
This perfectly can be seen in the sample export data you provided,
check here with jq - https://jqplay.org/s/7IdWrjX9kvf
