### ISSUE TITLE
Session button disappeared

### ISSUE THREAD

**Issue by robomonk1717** [cs0x7f/cstimer#334]
I can still use keyboard shortcuts to change sessions, but I can't create new sessions without changing my sessions for scramble switching to create a new sessions, and I can't delete old ones I don't want anymore.

**Comment by afedotov** [comment]
Just click on the upper-left corner of the time list panel, there is small quarter-circle toggle which shows/hides panel menu. Same toggle also exists on the other panels - scramble and tools.
