### ISSUE TITLE
Remove pin state from WCA-style clock scrambles

### ISSUE THREAD

**Issue by JustinTimeCuber** [cs0x7f/cstimer#349]
According to [Regulation F3](https://www.worldcubeassociation.org/regulations/#F3), altering pin states during inspection is now allowed, and pin states were therefore [removed from TNoodle](https://github.com/thewca/tnoodle-lib/commit/ebd36226284c9b57cd0655e5f5a75792d29d6d50).

**Comment by cs0x7f** [comment]
Fixed in https://github.com/cs0x7f/cstimer/commit/e6ceca397bf3fdb90a5cb2425488c8951ce36b1f
