### ISSUE TITLE
WCA penalties

### ISSUE THREAD

**Issue by casiku** [cs0x7f/cstimer#35]
Right now, you can only add one +2 penalty. Since it's possible to get multiple penalties in WCA regulations, I request adding multiple +2's (+2, +4, +6 etc) somehow.

**Comment by cs0x7f** [comment]
Interesting suggestion. Recorded in https://github.com/cs0x7f/cstimer/issues/22
Once WCA decides to accumulate all kinds of "+2" together, I counted that the penalty might be up to +16 for traditional events and more +2s for each almost-solved cubes in multi-BLD.
