### ISSUE TITLE
All times disappearing for random periods of time

### ISSUE THREAD

**Issue by fabio12345678910** [cs0x7f/cstimer#357]
At random times, all of my solving data disappears and is replaced by a single session. This session remains for a few hours and I am unable to move from this session, even after changing sessions. All my other sessions still exist and CStimer still knows how many solves are in each, but they are inaccessible since CStimer will always default to this new session at these times. 

When this is the case, the export button also loses all functionality, no popup window appears when I click it. 

I would appreciate a fix to this issue as it is quiet frustrating to lose all your times for a few hours fairly frequently. 

Thanks.

**Comment by cs0x7f** [comment]
Are you able to export your data to a txt file?

**Comment by fabio12345678910** [comment]
No, nothing happens when I click on the import/export button in the top left during these phases.

**Comment by cs0x7f** [comment]
Open the console of your browser (usually by pressing F12), is there any error log printed?

**Comment by fabio12345678910** [comment]
This is what i see when I look at the console

The FetchEvent for "https://hm.baidu.com/hm.js?474c635761856d5056d56c73b5e2fc4b" resulted in a network error response: the promise was rejected.
Promise.then (async)
(anonymous) @ sw.js:23
sw.js:29 
        
        
       Uncaught (in promise) TypeError: Failed to fetch
    at sw.js:29:11
(anonymous) @ sw.js:29
(index):63 
        
        
       GET https://hm.baidu.com/hm.js?474c635761856d5056d56c73b5e2fc4b net::ERR_FAILED
(anonymous) @ (index):63
k @ jquery.min.js:2
fireWith @ jquery.min.js:2
ready @ jquery.min.js:2
D @ jquery.min.js:2
timer.js:13 CSTimer+ running!
cstimer.js:806 The AudioContext was not allowed to start. It must be resumed (or created) after a user gesture on the page. https://goo.gl/7K7WLu
(anonymous) @ cstimer.js:806
call @ cstimer.js:42
(anonymous) @ cstimer.js:232
dispatch @ jquery.min.js:2
h @ jquery.min.js:2
trigger @ jquery.min.js:2
(anonymous) @ jquery.min.js:2
each @ jquery.min.js:2
each @ jquery.min.js:2
trigger @ jquery.min.js:2
p.fn.<computed> @ jquery.min.js:2
(anonymous) @ observer.js:28
setTimeout (async)
setScramblePreset @ observer.js:13
observer @ observer.js:215
scrambles @ init.js:44
(anonymous) @ timer.js:10

**Comment by cs0x7f** [comment]
cstime+ may be incompatible with the current version of cstimer.  Try turning it off and see if the problem persists.

**Comment by fabio12345678910** [comment]
This appears to have fixed it! Thank you for helping and creating such a great timer :)
