### ISSUE TITLE
Suggest: Virtual Replay

### ISSUE THREAD

**Issue by ZhongWei927** [cs0x7f/cstimer#367]
can be able to watch the virtual replay not only from the (x turns, x tps) hyperlink, which is limited to only exclusive for the last virtual solve, from the interface where you can comment, add penalty, and get the 1-solve stat. Maybe you can be able to import a solve from the review code too.

also sorry about submitting so many issues at once

**Comment by afedotov** [comment]
You can open Virtual Reply for any past solve, exactly from that popup dialog with solve information you mentioned. There is `Review` link. This is just another UI/UX issue which often confuses users. And this definitely need to be somehow reworked in the future.

<img width="576" alt="Screen Shot 2024-02-21 at 20 34 46 " src="https://github.com/cs0x7f/cstimer/assets/4266693/fc3d603d-1f8d-4296-b834-6e6b9a6f3d8c">
