### ISSUE TITLE
Reboot loop when page is refreshed with FTO scrambles

### ISSUE THREAD

**Issue by HAVANITE** [cs0x7f/cstimer#374]
https://github.com/cs0x7f/cstimer/assets/86987302/aaca0659-d467-4fa3-a0a6-8c00aca7ae33

**Comment by HAVANITE** [comment]
I was able to fix this by changing the scramble type using the keyboard shortcut, but still an issue

**Comment by cs0x7f** [comment]
It is recommended to disable cstimer plus and try again.
