### ISSUE TITLE
All solves wiped even though saved on WCA account

### ISSUE THREAD

**Issue by Bloopypoopy** [cs0x7f/cstimer#375]
I had 39000 solves on cstimer. This was the last image i could get of cstimer before it wiped. Even though i saved it to my WCA account, when i logged back in all my solves were gone. My sessions stayed and my colour format but only all my solves in 3x3 were wiped. Even 2x2 and pyraminx etc stayed. 

<img width="1280" alt="Screenshot 2024-02-03 at 8 12 02 am" src="https://github.com/cs0x7f/cstimer/assets/163835906/06c58e3f-fd19-4aea-a3df-b0998ae6d1dd">

Im not going to use cstimer again.

**Comment by cs0x7f** [comment]
Would you mind providing you WCA ID?

**Comment by Bloopypoopy** [comment]
2022CHEO01 is my WCA ID

**Comment by cs0x7f** [comment]
csTimer's server has only received less than 5k solves. As for why other solves were not uploaded, we are not sure whether it is related to csTimer+.
