### ISSUE TITLE
Suggestion/Bug - I try to report my feedback about usage and Timeout sleep of screen on Android device.

### ISSUE THREAD

**Issue by DjDiabolik** [cs0x7f/cstimer#377]
It's fantastic SITE/APP..... i have  start to usage this recently and at today i have it in every my device :)

I have to report one strange thing:
I use it from a Android Tablet... it's a LENOVO M10 FHD Plus (Exact model TB-X606F) whit latest available official android patch (android 10 if i remember)
On this tablet, using Chrome, i have "installed" the APP by browser chrome and it's simply add to my "Home".

This "app" it's fantastic timer but there's a present a very usefull feature:
On Android it's setted a screen timeout after one minutes of inactivity. YEAH.. it's fantastic because when the "app" CStimer it's opened (also if open directly from a chrome tab) the screen never goes in sleepdown and remain ever turned on.

Instead this feature apparently it's not works in other my device:
For example i have a Samsung NOTE 4 whit a custom rom... a lineageOS android 11 roms. Also here the display timeout it's setted at 30 seconds of inactivity.
Here it's present the actual Firefox Browser and i have made same way:
- Open "cstimer.net/new" -> Tap option and choose "Install"
Also here the "app" cstimer it's be added to my home but here..... when the timer it's started the screen goes in timeout after the setted 30 seconds (and also goes in lock lol).

At this point is the question:
It's the browser Firefox not have this feature ? It's Android 11 respect Android 10 it's different ? 

Or it's simply the roms of different device can handle this feature ?

**Comment by afedotov** [comment]
The csTimer is using [Screen Wake Lock API](https://developer.mozilla.org/en-US/docs/Web/API/Screen_Wake_Lock_API) to prevent device from sleeping. Unfortunately this API and functionality is not supported in every browsers/platforms in the wild. And this is much that csTimer can do to prevent device from sleeping. If your browser does not support WakeLock, you only can adjust global system settings to prevent device from sleeping.

**Comment by DjDiabolik** [comment]
> The csTimer is using [Screen Wake Lock API](https://developer.mozilla.org/en-US/docs/Web/API/Screen_Wake_Lock_API) to prevent device from sleeping. Unfortunately this API and functionality is not supported in every browsers/platforms in the wild. And this is much that csTimer can do to prevent device from sleeping. If your browser does not support WakeLock, you only can adjust global system settings to prevent device from sleeping.

Great explanation... at this point Chrome suport this API... apparently Firefox no :) 
But it's strange your link redirect to mozilla support then in their browser the same thing doesn't work... lol.
