### ISSUE TITLE
import sessions

### ISSUE THREAD

**Issue by wht003** [cs0x7f/cstimer#378]
As far as I see, there is no way to import sessions in any way.
I used CStimer on different devices and now I can't put the sessions from the one device to the other without removing the existing sessions.
Also, you can export sessions as an CSV file but you can't import a CSV.

I'd like to have a wayto do so.

**Comment by cs0x7f** [comment]
You can import session without reset other options or sessions by EXPORT -> "import session(s) from other timer". It also works for cstimer exported files.

**Comment by wht003** [comment]
Oh, I see. Thank you!
