### ISSUE TITLE
Latest update removes clearing session

### ISSUE THREAD

**Issue by Mollerz** [cs0x7f/cstimer#38]
I was planning on clearing out my current sessions ready for the new year but I am unable to delete all times from a session now. Alt+d now adds a session as the hotkey is linked to the button (I believe).

I would still like to be able to keep the session but delete all times within it.

**Comment by cs0x7f** [comment]
Since all times have been removed, what's the difference between a new session and a cleared session?

**Comment by cs0x7f** [comment]
After some of today's commits (not updated to https://cstimer.net/ but works in https://cstimer.net/new/ ), when you click '+', all settings including scramble/session name/multi-phases are copied to the new session. 
In this way, the only difference is that the old session is lay in the session manager (and you can delete it later).

**Comment by cs0x7f** [comment]
Finally, I add another option that you are able to directly delete a session after you click '+' to add the new one, which is the same effect as clear the session. The only difference is that, if you click cancel in the confirmation dialog, the new session is still created and the old session is archived.

**Comment by cs0x7f** [comment]
Well, finally I revert the 'X' button back in https://github.com/cs0x7f/cstimer/commit/245a7fab97695a8919537931522e66b85c5b5569
