### ISSUE TITLE
Feature request: Add support for QiYi Smart Cube

### ISSUE THREAD

**Issue by Entoryvekum** [cs0x7f/cstimer#380]
QiYi Smart Cube(QYSC) has gained a number of users and I wish I could use QYSC in cstimer.

**Comment by cs0x7f** [comment]
An employee of qiyi told me that the data from qiyi is encrypted, and they don't want to make it connect with csTimer.
Even putting aside legal issues, it is very difficult to crack an encryption scheme in a short period of time. I personally do not have such ability, I can only hope that someone in the open source community has such ability.

**Comment by zrainx** [comment]
Why this issue is closed?
