### ISSUE TITLE
Feature request: Add support for QiYi Smart Cube 

### ISSUE THREAD

**Issue by zrainx** [cs0x7f/cstimer#382]

**Comment by Entoryvekum** [comment]
The previous issue was close for the following reasons:
1. The data from the QYSC is encrypted which makas it impossible for cstimer fetch the moves of the cube.
2. @cs0x7f had made contact with Qiyi and leant that Qiyi didn't seem to want to allow connecting QYSC to cstimer.
3. Qiyi's employee says that they don't time to consider it since QYSC has only been on the market for weeks. And have urgent problems pile up so they don't have enough manpower to work with cstimer's author.
4. Qiyi's employee claim that to make QYSC to connect with cstimer requires a lot of work and communication, they will consider such feature when they have time.

**Comment by Entoryvekum** [comment]
![图片](https://github.com/cs0x7f/cstimer/assets/20198566/d4d92920-1b87-47f2-bdf7-c430a3563da7)
![图片](https://github.com/cs0x7f/cstimer/assets/20198566/068b2903-212e-4f99-a827-8fda75723df2)

**Comment by cs0x7f** [comment]
My personal preference is that they don't want third party software to interface with their hardware (whether it's a timer or a smart cube). As for "no time", their smart timer has been on sale for almost a year. As long as they are willing, I think we can complete the understanding of the protocol within half a day, and the rest will be development work on csTimer side.

**Comment by Entoryvekum** [comment]
> My personal preference is that they don't want third party software to interface with their hardware (whether it's a timer or a smart cube). As for "no time", their smart timer has been on sale for almost a year. As long as they are willing, I think we can complete the understanding of the protocol within half a day, and the rest will be development work on csTimer side.

There's no need to encrypt these data in the first place. Why would you encrypt something anyone in the room can see with their own eyes? Is your cubing performance something you must conceal? I would rather believe that they pursue a close software ecosystem even if there software is still far from mature.

**Comment by afedotov** [comment]
No single smart cube protocol was opened to 3rd party by manufacturers. And most of them are encrypted. All things was done just with pure hacker enthusiasm using reverse engineering. And encryption made just to harden that reverse engineering process.

Technologies used by QiYi makes reverse engineering way harder. So don't expect that support for QiYi smart hardware will come to 3rd party software in foreseeable future.

**Comment by Flying-Toast** [comment]
Ok, so far what I've found (sharing it here if anyone can help take it further):

-  the encryption used is AES-128 with the fixed key `f2569ab4d04e387218ceae18a210` (as taken from decompiled android app). But I'm still not sure how the IV is determined.
- Before the cube will send any face turn notifications, you have to perform 2 writes on the `fff6` characteristic:
- - write the value `6ed6ddbffbb060b7f80eb5860c157a50e0a67c0dc97d5a21b1d904e03e8a099c` (32 bytes)
- - write the value `490ce0cd853d6895ce6d68e525aa6038` (16 bytes)
- - these values seem to change for each connection, so maybe the IV is included somewhere in here?
- Face turns are broadcast as notifications on the `0000fff6-0000-1000-8000-00805f9b34fb` characteristic. The cube will keep re-sending the same message until you write some sort of ACK (16 bytes) to the `fff6` characteristic. I'm not sure about the format of this ACK.

**Comment by cs0x7f** [comment]
> @afedotov Speficially which technologies do they use that would make it harder to reverse engineer? I'm just getting the QiYi smartcube and may have gotten nerd sniped...

There's a discord server for bluetooth cubes: https://discord.gg/RsHv4rbu

**Comment by Flying-Toast** [comment]
Coming soon to a cubing timer near you ;)

https://github.com/cs0x7f/cstimer/assets/38232168/02f63778-3bea-4d3b-a3af-fd7c5b0c09e7
