### ISSUE TITLE
Millisecond rounding issue

### ISSUE THREAD

**Issue by xsrvmy** [cs0x7f/cstimer#386]
It seems like there is some inconsistency with turning millisecond on and off and the rounding when it comes to updating averages. Eg. If I enter 1.006 5 times without milliseconds, then turn on milliseconds, I have to refresh the page before the ao5 says 1.006 instead of 1.000.

**Comment by cs0x7f** [comment]
Fixed in https://github.com/cs0x7f/cstimer/commit/97f9e084ca0a380a6c8a503586146df2e3ea4e52
