### ISSUE TITLE
suggestion: "print comments in statistics"

### ISSUE THREAD

**Issue by kais184** [cs0x7f/cstimer#387]
add option to remove comments from statistics (similar to with scrambles/solving date) so that it's easier to just copy+paste the list of times (i add comments to most of my solves and have to manually delete the comments every time whenever I want to do this)

**Comment by cs0x7f** [comment]
Implemented in https://github.com/cs0x7f/cstimer/commit/1c12051855104d1e5d6596a4d580d989f1fbe68e
