### ISSUE TITLE
Solves were deleted

### ISSUE THREAD

**Issue by Facks101** [cs0x7f/cstimer#389]
When I would click on a different session to switch what cube I was solving the times that I had from the previous session stayed. I would click on my 5x5x5 session and my times from clock would show up and if I clicked on any other session only my clock times would show up. I exited out of cstimer and reopened it and all of my solves were gone. I had an export from a couple weeks ago so I didn't lose all of my times but I still lost a lot of times.

**Comment by cs0x7f** [comment]
csTimer's data is stored in your browser, and there is nothing we can do if it is not backed up.
