### ISSUE TITLE
Scrambles under "WCA" do not follow WCA order

### ISSUE THREAD

**Issue by Mollerz** [cs0x7f/cstimer#39]
WCA order is:

3x3, 2x2, 4x4, 5x5, 6x6, 7x7, bld, fmc, oh, wf, clock, mega, pyra, skewb, sq1, 4bld, 5bld, mbld.

**Comment by cs0x7f** [comment]
Fixed in https://github.com/cs0x7f/cstimer/commit/03975366cde0dfefe01612e1d76144243fd71a43.
