### ISSUE TITLE
cstimer_module compatibility with TypeScript

### ISSUE THREAD

**Issue by peacehh** [cs0x7f/cstimer#390]
When importing from a TypeScript file using the following 

`import cstimer from 'cstimer_module'`

the following error is raised 

Could not find a declaration file for module 'cstimer_module'. 'c:/Users/findh/Downloads/DCCDiscordBot-main (1)/DCCDiscordBot-main/node_modules/cstimer_module/cstimer_module.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/cstimer_module` if it exists or add a new declaration (.d.ts) file containing `declare module 'cstimer_module';`

**Comment by cs0x7f** [comment]
Should be fixed in https://github.com/cs0x7f/cstimer/commit/3aaecd431e521d04503f6408322279b0c9515f97 (module version 0.1.1)

**Comment by cs0x7f** [comment]
Reopen the issue if any error is still raised.
