### ISSUE TITLE
Turns count and TPS in stats table

### ISSUE THREAD

**Issue by qmegas** [cs0x7f/cstimer#391]
As an owner of smart cube it's nice that I may see turns count and TPS in reconstruction tool. But I also interesting to get summary of these metrics over training session. Is it possible to add that metric to stats table metric selector (the one that allows to choose between time and different CFOP stages)? Or maybe simply add another tool which does that?

**Comment by cs0x7f** [comment]
Implemented in https://github.com/cs0x7f/cstimer/commit/c4a0e771d410d27a9f0715b32f3abf92af03b199
