### ISSUE TITLE
Color Option for Record Times?

### ISSUE THREAD

**Issue by ajhtwin** [cs0x7f/cstimer#392]
Currently, the color for record times can be one of 4 things: red, bolded, nothing, or the same as your link color. It really makes no sense to me why there isn't an individual setting for this, especially because there are already so many color options. Why if I want to make it gold for example does all the links on the site have to also be gold? please add in a designated color setting.

**Comment by cs0x7f** [comment]
The main reason was that it was not compatible with the color matching links that had been shared before.
And at the time I was not sure whether it would be a popular feature, so I did not dare to adjust the format of the shared link easily.
