### ISSUE TITLE
cheaters in online competition

### ISSUE THREAD

**Issue by hummmcubos** [cs0x7f/cstimer#398]
There are people who put insane times in online competition with an average of 0.1s in 3x3, something that no professional has ever done. These people, when we look at the WCA profile, we discover that they are usually children, I can see from the photo, and they usually ride in an average of 30 seconds. Furthermore, these people perform several other averages in competitions that do not match their averages in recent championships, like someone who mounts in 20 seconds, dropped to an average of 5 seconds in a month, for example.

I don't know anything about programming but if it were possible to create a method of reporting practices like this I would appreciate it.
  
There are always two people cheating on their profiles: 2023POOI01 and 2024WALT09. In addition to others.

**Comment by cs0x7f** [comment]
This function is only to allow cubers to have some common scrambles. There will be no rewards regardless of the final ranking. If someone can really gain something from self-deceiving cheating, then let them be.
