### ISSUE TITLE
Support for Weilong V10 AI smart cube

### ISSUE THREAD

**Issue by smurfsmurf** [cs0x7f/cstimer#399]
No bluetooth devices show up when trying to pair with the new Moyu weilong V10 smart cube.
I think there's no driver for it on cstimer. I can find and connect to the cube on Cubeast but it then tells me that the cube is not compatibie with Cubeast.
I'm not sure if this cube (with bluetooth device name WCU_MY32_XXXX) uses the same protocol as the older Moyu AI cube. Would love to see support for it!

**Comment by 10a5er** [comment]
+

**Comment by 10a5er** [comment]
Did something happen? Was support for it added? Im still waiting with ordering my V10Ai until CStimer is fully compatible.
