### ISSUE TITLE
Remove last solve shortcut not working

### ISSUE THREAD

**Issue by ProsperHuang** [cs0x7f/cstimer#403]
I'm on windows 11, and the ALT+Z shortcut isn't working to delete the last solve. I noticed this maybe about 1 month ago.

**Comment by cs0x7f** [comment]
I can't reproduce your bug, maybe your other software has occupied this shortcut key (such as geforce experience)

**Comment by ProsperHuang** [comment]
I had the geforce open overlay shortcut binded to alt+x for months just for this reason. I don't know what changed but anyway i somewhat fixed it. I have to do shift+alt+z instead to delete the last solve. (doesn't allow me to delete the last x solves which i believe was possible before)
