### ISSUE TITLE
Timestamp displayed 3 times for single solve details

### ISSUE THREAD

**Issue by tussosedan** [cs0x7f/cstimer#41]
Generated By csTimer on 2018-12-12 (solving from 2018-12-08 17:52:25 to 2018-12-08 17:52:25)
single: 2.70

Time List:
1. 2.70   @2018-12-08 17:52:25

**Comment by cs0x7f** [comment]
Seems that the solving date information in the title should be removed when date of each solving is appended?

**Comment by tussosedan** [comment]
No, the range is helpful. It's just when they're all the same, for one solve :)

**Comment by cs0x7f** [comment]
Just for single? How about mo2?

**Comment by tussosedan** [comment]
Okay you're right, mo2 too, heh.

**Comment by cs0x7f** [comment]
Done in https://github.com/cs0x7f/cstimer/commit/9d9dc0f77af04537a9ee6173a9d4e2fb721b42f3
