### ISSUE TITLE
EOLS generating same LS case

### ISSUE THREAD

**Issue by NucleaRaven** [cs0x7f/cstimer#411]
3x3x3 (CFOP) > EOLS subset always generates case SPGO-17. Even when manually disabled, this is the only LS case that will come up. The resulting last layer after is correctly randomized, just the last slot case is not.
![IMG_1839](https://github.com/user-attachments/assets/2e239344-9ca4-47f9-b026-de7015da8d91)
![IMG_1838](https://github.com/user-attachments/assets/60ec5032-3f75-4af2-abb0-4b9838c9a21d)

**Comment by cs0x7f** [comment]
Thank you for the bug report.
It's fixed in https://github.com/cs0x7f/cstimer/commit/00c45bccc7d4d7f46307aa4dcc7956c04045ec2c
