### ISSUE TITLE
Keep App Awake While Timer Is Running

### ISSUE THREAD

**Issue by jwedel** [cs0x7f/cstimer#413]
I have csTimer as a homescreen app on my iphone.

when I start the timer, the screen goes black before I am finished. Yes I am that slow.

There is browser api to prevent this:

https://developer.mozilla.org/en-US/docs/Web/API/Screen_Wake_Lock_API

I am not sure if this was considered already.

if not, I could also try to contribute with some guidance.

Cheers!

**Comment by jwedel** [comment]
I found code that already uses the wake lock. So either it’s a configuration issue (couldn’t find anything) or it is not working on my iPhone / safari.

**Comment by afedotov** [comment]
This is already implemented on the csTimer side.
Unfortunately at present this API not fully supported on iOS. The link you referred contains browser compatibility table where stated about [WebKit bug 254545](https://webkit.org/b/254545#c32).
