### ISSUE TITLE
draw scramble issues

### ISSUE THREAD

**Issue by moss-ss** [cs0x7f/cstimer#414]
There are 2 draw scramble options, and both of them aren't working for NxNxN, and NxNxN types such as oh and bld, and pyraminx and skewb

tl;dr: 2 draw scramble options, dosen't work for NxN, pra and skewb

note: upon refresh it appears and then goes away

https://github.com/user-attachments/assets/1eb2e3af-09d9-4a77-9990-443f6300ed63

**Comment by moss-ss** [comment]
note to add: it briefly appears upon refresh then dissapears

https://github.com/user-attachments/assets/5b81b754-56c7-4399-aab6-af6887df026f

**Comment by afedotov** [comment]
Please uninstall the csTimer+ extension.
It is outdated, and not compatible with current csTimer version.

**Comment by moss-ss** [comment]
> Please uninstall the csTimer+ extension. It is outdated, and not compatible with current csTimer version.

thank you
