### ISSUE TITLE
Update EOLine state to EOCross

### ISSUE THREAD

**Issue by NucleaRaven** [cs0x7f/cstimer#418]
3x3x3 CFOP > EOLine is obselete as EOCross is the speed optimal approach to ZZ in modern day.
I propse updating this to EOCross, or at least providing the option for either.

**Comment by cs0x7f** [comment]
Implemented in  https://github.com/cs0x7f/cstimer/commit/1b22cf3a4df017edb69f448f9bfcebeee90fb944
Thanks for your suggestion.
