### ISSUE TITLE
Custom Statistical indicators

### ISSUE THREAD

**Issue by topppits** [cs0x7f/cstimer#42]
option -> statistics -> Statistical indicators -> Custom
isn't working on https://cstimer.net/new/

edit:
Also when I switch from https://cstimer.net/ to https://cstimer.net/new/, tools aren't working anymore: on the right bot of the the screen they are just gone and a click on tools does nothing. Mouse over the tools button just shows a blank box. In the options -> tools I can only see time distribution precision, nothing else. Same if I go to https://cstimer.net/new/ and import a backup that I made with https://cstimer.net/.

**Comment by cs0x7f** [comment]
Thanks for the bug report. Fixed in https://github.com/cs0x7f/cstimer/commit/a9aea99660421ebf8b38646cbee01d7b83d24bb9
