### ISSUE TITLE
Training Stat tool for ZBLL cases

### ISSUE THREAD

**Issue by RayVinceOng** [cs0x7f/cstimer#422]
The training stat tool appears to not properly sort ZBLL cases appropriately. 

For example this L-case scramble: D' B2 D' F2 D2 B2 U B2 U B2 U B D F2 D' B' -> sorts into a G-perm (O2-60) instead of the right case (L4-5).

Also would it be possible to add ZBLL cases to the Reconstruct tool?

**Comment by cs0x7f** [comment]
Done in https://github.com/cs0x7f/cstimer/commit/97d89a975377bf0a3f042a1a0859ff18dffc3365
