### ISSUE TITLE
standardize FTO virtual keybinds

### ISSUE THREAD

**Issue by effperm** [cs0x7f/cstimer#423]
people have noticed that some of the moves are being done by relatively different keys (specifically the rotations and moves at the back) compared to what [aedan bryant's fto simulator](https://youtu.be/QXAGFxLRi14?si=VAwWGfmFg7qSWJS8) has been doing which is pretty old but was very much used as a virtual fto at the time so it would be nice to just make them exactly the same as something that most virtual solvers of that simulator would be familiar with

references of all keybinds from the code: (π means that aedan hasnt put a key for that specific move, so you have a little bit of freedom there)
![image](https://github.com/user-attachments/assets/4606892d-c6d0-430a-a663-6276d2ffae23)
![image](https://github.com/user-attachments/assets/f593162c-9634-4825-921f-f403ae807bee)

**Comment by cs0x7f** [comment]
Done in https://github.com/cs0x7f/cstimer/commit/c5903b627f0d780c6461ab121bd8962f3bae365d
Current key mappings are:
I:R K:R' D:L E:L' J:U F:U' H:F G:F' S:D L:D' W:B O:B' 8:BR ,:BR' C:BL 3:BL' U:Rw M:Rw' R:Lw' V:Lw Y:[R] N:[R'] T:[L'] B:[L] ;:[U] A:[U'] P:T Q:T'
