### ISSUE TITLE
Draw Scramble Tool not working

### ISSUE THREAD

**Issue by calebgp** [cs0x7f/cstimer#425]
My timer doesnt show the scrambles
![Screenshot 2024-09-04 at 11-35-17 csTimer - Professional Rubik's Cube Speedsolving_Training Timer](https://github.com/user-attachments/assets/56951ad2-a80c-4398-966d-3d94508e5d7a)

**Comment by cs0x7f** [comment]
Disable cstimer plus and try again.

**Comment by calebgp** [comment]
It worked! Do I need to use without cstimer plus then?

**Comment by calebgp** [comment]
![imagem](https://github.com/user-attachments/assets/6eb6a80e-d77b-49f1-aeea-a35d8d67218d)
