### ISSUE TITLE
padding for subset scrambles?

### ISSUE THREAD

**Issue by effperm** [cs0x7f/cstimer#427]
sometimes its really to see the optimal solution of a 3x3 subset scramble just by looking at the scramble because they give the shortest path to scramble (provided that they are random state of course)

this can range from lse, (yes even the non <M, U> scrambles can give silly stuff as well, just tried a few solves and got U L2 R2 D' x2 and a few others which didn't really allow me to see the optimal solution but were easily see through like domino moves into basically M U M') <R, U> to an extent, and also the domino subgroup if you're trying to FMC it and especially the half turns only scrambles

this could easily be resolved by just having some sort of eo-breaking sequence at the very start of every scramble, which is what the FMC scrambles have including the ones for sliding puzzles

so yeah lol

**Comment by cs0x7f** [comment]
There is indeed a contradiction between scrambling efficiency and revealing the optimal solution. At present, the most appropriate approach I can think of is to limit the shortest scrambling length.
