### ISSUE TITLE
Moyu weilong v10 ai standard not connecting

### ISSUE THREAD

**Issue by RayVinceOng** [cs0x7f/cstimer#428]
My Weilong v10 AI standard version isn't connecting to cstimer, I believe this is because the Bluetooth device name is "WCU_MY33..." as opposed to "WCU_MY32...".

**Comment by cs0x7f** [comment]
Updated in https://github.com/cs0x7f/cstimer/commit/dcbed4d2b74b63297a4350727da25814b11dfba0
