### ISSUE TITLE
Custom cycle break order in bld helper tool

### ISSUE THREAD

**Issue by wilkojc** [cs0x7f/cstimer#429]
Per title - is it possible to specify a custom cycle break order for edges and corners while using the BLD Helper tool?
While it is possible to specify a custom lettering scheme, buffers and other great stuff pertaining to generating the scrambles themselves, I see no option to change the cycle break order.
If it is not possible, what is the default order being used? Could a custom order be implemented?

**Comment by cs0x7f** [comment]
Done in https://github.com/cs0x7f/cstimer/commit/d5d1691a7893ef8fadcbb83c9510c56904697500

**Comment by wilkojc** [comment]
@cs0x7f Not sure how to get this working correctly, or simply my understanding is flawed.
Consider this scramble (corners only)
U2 B2 D2 B' F2 D2 L2 B' U2 L2 U2 R' B L' D2 L' B' R

With default cycle break order (U > F > D) the memo looks like this
C: OD SD AN AV GV 

With the cycle break order I supplied (CBPOGHAD CQPFNHMEOGKS) the generated order looks like this
C: OB EB VG VZ FZ 

Following the supplied order I would expect a memo of
C: OB EP UP HI

My buffer is UFR (C speffz) for corners and UF (C speffz) for edges.
Putting C as the first or last target did not seem to matter when the C sticker is also specified as a buffer in BLD helper settings.
![image](https://github.com/user-attachments/assets/d3ee60b0-9112-4920-b3ac-ebd6ab719956)

**Comment by cs0x7f** [comment]
I wonder, if you directly perform algorithms corresponding to the mark "C: OE BP UP HI" on the scrambled cube without cycle-break informations, how can you solve the cube?

**Comment by wilkojc** [comment]
> I wonder, if you directly perform algorithms corresponding to the mark "C: OE BP UP HI" on the scrambled cube without cycle-break informations, how can you solve the cube?

I wasn't sure which one of the two I supplied would be correct, I think you are correct in implying you cannot solve this way.
The correct memo would be
C: OB EP UP HI
The question on how to correctly pass in the cycle break order or if the code itself needs a fix remains though

**Comment by cs0x7f** [comment]
As far as I know, each letter of the bld encoding represents a swap of buffer and the cubie of the code, so the following encodings correspond to the combination of these permutations:
OB EB VG VZ FZ
= (C, O, B) * (C, E, B) * (C, V, G) * (C, V, Z) * ​​(C, F, Z)
= (C, O)(B, E)(V, G)(F, Z)
where (x1, x2, ..., xn) means moving x1 to x2, moving x2 to x3, and so on.

However,
OB EP UP HI
= (C, O, B, E, H, I)(P, U)
Obviously, it is different from the above permutation structure, so it is impossible to solve the state.

**Comment by wilkojc** [comment]
Unfortunately what you are saying is going over my head, however I don't think it matters much.

I think the code is written in a way that does not discern between specific stickers of a given cubie.

It treats K and P as it would be V. Those are different stickers of the DFR corner.
If you supply K or P into your cycle break order, any time the cycle break would be of those values, V will be used instead.

This is true for other letters as well. I suppose it is linked to how the lettering scheme is a triplet/pair. If you want any of the letters for a given triplet/pair to be a used as a cycle break target, but it is not the first on the letter scheme list then the first letter will be chosen anyway. 

Consider by lettering scheme (X swapped for Z)
CJM DIF ARE BQN VKP ULG ZSH WTO BM CI DE AQ VO UK ZG WS JP

If the supplied cycle break order would contain I or F, then D would always be used in it's place.
Same thing is happening in my example, where despite providing P in the cycle break order, V is being used, as it is first from VKP triplet.

Another evidence for this behaviour would be that if you paste in the default cycle break order of:

CDABVUZW BCDAVUZWJLRT

then your selection in the tool window would be marked as `U > D > E` instead of `Customed` which makes sense, since it is the default value. 

However if you use this sequence (which uses the same "order" of pieces, but it uses different stickers of a given piece, so for CJM it uses M instead of C, for DIF it uses F, and so on...):

MFENPGHO MIEQOKGSPFHN

and paste it into the custom break box, the selection will still show you chose `U > D > E` as if it were the default value, because the order of **cubies/pieces** did not change, however the **sticker** order did change. You would perform a different algorithm for shooting from your buffer to V and a different algorithm for shooting to P, even though they are the same piece, they each correspond to a different sticker/side of the piece.

Lastly, if you do alter the order of the sequence itself, it will not be marked as `U > D > E` anymore, but `Customed`. Consider this example, where first two letters of the default cycle break order are swapped:

DCABVUZW BCDAVUZWJLRT

Here's a gif that portrays the situation. I think the distinction between different stickers of the same piece would have to be somehow implemented for a fully custom cycle break order to work.
![Animation](https://github.com/user-attachments/assets/ead2be0c-fe00-4215-bcce-4b2d6b31c54d)

**Comment by wilkojc** [comment]
@cs0x7f Is this something that you're planning to work on in the future?

**Comment by cs0x7f** [comment]
> @cs0x7f Is this something that you're planning to work on in the future?

Yes, I understand your request and I am trying to find a solution.

**Comment by wilkojc** [comment]
Thanks for the info and your time. Good luck as this seems like a complicated issue

**Comment by cs0x7f** [comment]
Fixed in https://github.com/cs0x7f/cstimer/commit/5e0ed072a4756d328e911ebb1c2fb29719a22d6a
