### ISSUE TITLE
Allow all edges/corners to be fixed with a single keyword in BLD Helper

### ISSUE THREAD

**Issue by wilkojc** [cs0x7f/cstimer#430]
Currently if you want to generate edge only or corners only scrambles using BLD Helper tool, you need to specify each of the pieces separately eg. UF UR UL UB DF DR DL DB FL FB BL BR for edges in the "fixed" field.
I propose adding an "all" keyword or something of the like to serve the same purpose - make all the possible edge/corner pieces fixed during scramble generation.
This would only be a QoL change, as the main functionality is present.
![image](https://github.com/user-attachments/assets/081dbfc3-95d3-4da6-a852-1a8a4b3903ab)

**Comment by cs0x7f** [comment]
If you want all edges or corners to be solved, you can change the "Corner" or "Edge" to solved, or set #codes of corners or edges to 0-0.

**Comment by wilkojc** [comment]
This is great, thank you.
