### ISSUE TITLE
Can't see scramble images in cstimer+

### ISSUE THREAD

**Issue by An-Average-Italian** [cs0x7f/cstimer#431]
Since at least a week, I've been unable to see scramble images in certain events that should support them.

The ones I **can** see are the following:

- Clock
- Megaminx
- Square-1 and Square-2
- 15-puzzle and 8-puzzle

I've got Windows 11 and I use Chrome, if that helps

**Comment by cs0x7f** [comment]
Disable cstimer plus and try again.

**Comment by moss-ss** [comment]
I had the same issue. Remove CStimer+ as it is outdated and if you want a modern ui use cstimer.net/new/ and go into display settings, UI design is: CStimer+
