### ISSUE TITLE
Draw scramble tool doesnt work on my cstimer

### ISSUE THREAD

**Issue by Jayodhya-cubing** [cs0x7f/cstimer#432]
It just doesn't work on cstimer+. The scrambles aren't shown in every event except square 1 and megaminx

**Comment by cs0x7f** [comment]
Disable cstimer plus and try again.

**Comment by cs0x7f** [comment]
> > Disable cstimer plus and try 
> It works.but I need cstimer+ though

cstimer+ wasn't developed by me, so there's nothing I can do about it either. Can you tell us what features you want it to be?

**Comment by Jayodhya-cubing** [comment]
The tingman and other youtubers sounds in inspection
