### ISSUE TITLE
Issues using Gan 356 iCarry

### ISSUE THREAD

**Issue by Aityz** [cs0x7f/cstimer#436]
Hello! I got a Gan 356 iCarry today, however I am having difficulties using it with cstimer, on MacOS Sequoia, Chrome 129.0.6689.80, with the correct flags enabled. The error is: ``NotFoundError: No Services matching UUID 0000fff0-0000-1000-8000-00805f9b34fb found in Device.``. 

If the iCarry is not supported, I am willing to write support for it, and push it upstream. Thank you.

**Comment by cs0x7f** [comment]
There are many versions of Gan Cube, and iCarry also has multiple versions.
What is the device name of your cube?

**Comment by cs0x7f** [comment]
In addition, if the current beta version does not support the iCarry you have, and you are capable of implementing that, I will merge your PR into the main branch asap.

**Comment by Aityz** [comment]
On CubeStation it is listed as "GANic4FN", does CSTimer currently have support for this model?

**Comment by cs0x7f** [comment]
Yes, it should be supported. Maybe it is a problem in other links (such as browser or Bluetooth hardware).

**Comment by Aityz** [comment]
Alright, thank you~

**Comment by afedotov** [comment]
@Aityz Is the problem solved and you able to connect using csTimer beta version here: https://cstimer.net/new/ ?
If not, can you provide exact model name of your iCarry cube: iCarry, iCarry S, iCarry 2, iCarry E?

If you have connection problem, can you put here bluetooth debug log:
- Enable "Bluetooth Cube" tool
- Reload csTimer page
- Try to connect the Cube
- Open bluetooth debug panel by clicking "chip" button and copy debug log

<img width="245" alt="ble-debug" src="https://github.com/user-attachments/assets/be1d2b1b-65b6-4f02-8757-71f987db774f">

**Comment by Aityz** [comment]
It is working, thank you!
