### ISSUE TITLE
A lot of scramble types in the cstimer module don't work.

### ISSUE THREAD

**Issue by Leefmans** [cs0x7f/cstimer#439]
I installed the module in my directory using npm.
I  have this node js code that i can run to call a scramble:

```
const cstimer = require('cstimer_module');

async function getScramble(type) {
    try {
        const scrambleTypes = await cstimer.getScrambleTypes();
		console.log(scrambleTypes);
        const scramble = await cstimer.getScramble(type);
		console.log(type + ": " + scramble);
    } catch (error) {
        console.error("Error getting scramble:", error);
    }
}

// Call getScramble with command-line arguments
const args = process.argv.slice(2);
getScramble(args[0]);
```

a lot of wca scrambles work but for example 555wca, 666wca and 777 wca don't.
Some of them return errors like 555bld, others just don't do anything.

**Comment by cs0x7f** [comment]
For most of scramble types, the second parameter (length of scramble) of getScramble should not be undefined.

**Comment by Leefmans** [comment]
Hi, thanks for your help, everything works with the second parameter.
But now i have another question because i saw that a lot of scrambletypes have an extra value in: https://github.com/cs0x7f/cstimer/blob/master/src/lang/en-us.js
Is this what i should use as second parameter, because there are also negative value's

**Comment by cs0x7f** [comment]
Yes, if it is negative, use its absolute value

**Comment by Leefmans** [comment]
Ok, thanks a lot for your help!
