### ISSUE TITLE
Add timestamp to export file name

### ISSUE THREAD

**Issue by tussosedan** [cs0x7f/cstimer#44]
A small request, please add:
1. A timestamp to the full JSON export file name. 
2. Session name and timestamp to session CSV export file name. And maybe some indication if it's a full or partial session export. 

I believe would be best to use something like the YYYY-MM-DD HH-MM-SS format for clarity and natural sorting.

**Comment by cs0x7f** [comment]
Done in https://github.com/cs0x7f/cstimer/commit/7ce129f0efb35b61e15419f46a91b74325d8e299
I use YYYYMMDD_HHMMSS for a secure file name, since it might be better not to use space for convenience of post processing.

**Comment by tussosedan** [comment]
Wooo that was fast! Yeah that format is great.
No way to securely add the session name for the CSV, though?

**Comment by cs0x7f** [comment]
Yes. For example, if the name contains some characters like '/' and '*', it must be an invalid file name for almost all platform. Furthermore, the csv exportation also works for cross-session statistics (which has been clickable and exportable after a commit yesterday), wherein session name is not well defined.
