### ISSUE TITLE
Feature request: Time the pauses

### ISSUE THREAD

**Issue by nmonserrato** [cs0x7f/cstimer#440]
Hey :wave: 
Here's what I'm thinking. I rarely practice in a good way, slowing down and looking for better solutions or trying to look ahead. Timing myself is much more exciting since at any time I can break my PBs, and if I have a few mins break from work I go for that!
So now after 15 years of cubing I'm stuck on a 16s avg exactly like I was 14 years ago :sweat_smile: 

I recently bought a smart cube and the support in cstimer is great, I can even see how long each step takes me, number of moves, tps, etc. There's a lot of potential data.

So I've been thinking what if, instead of timing how long it takes me to solve the cube, I time how much I pause? Or how many moves it takes me to solve the cube?
For pauses I think recognition is what takes me longer, but we could sum everything if it's easier.

This way, I would have the challenge to beat my PRs, but to beat them I must improve the look-ahead, slow down and be smoother, learn 2-side recognition, etc. Number of moves could be useful to force me to find better solutions for cross, F2L cases, or be motivated to learn full OLL, and at the same time not having the pressure of the time ticking.

I forked the code and I'm trying to study it, but I'm terrible at javascript and it could probably take me months to come up with a PR that works. 
What I have in mind is having a subset of the 3x3x3, and when that is selected the something else is "timed".

What do you think? Would it be hard to implement?

**Comment by cs0x7f** [comment]
Currently, the "insp" column in "reconstruct" tool denotes pause time between steps. There are per-solve data and per-case data (pause time for each oll or pll case in your solves). Reopen the issue if this function does not meet your needs.
