### ISSUE TITLE
can't see draw scramble

### ISSUE THREAD

**Issue by hardcoding09** [cs0x7f/cstimer#445]
when i log into cstimer, draw scramble appears for a moment then it disappears, and until i relog into cstimer i can't see scramble image, and even when i log into cstimer, scramble image appears for a moment, and then it disappears.
![screenshot_08112024_004856](https://github.com/user-attachments/assets/fd295744-f2a4-4474-a94e-2292ba609354)

**Comment by topppits** [comment]
disable cstimer+. It's not compatible anymore and the devs apparently don't develope it anymore. There are multiple issues asking this exact question.
