### ISSUE TITLE
Unable to connect hardware timer to csTimer

### ISSUE THREAD

**Issue by kits** [cs0x7f/cstimer#448]
Connection between Android smartphone and hardware timer (YuXin Timer V2) using cstimer_stackmat.apk is no longer possible.
https://github.com/cs0x7f/cstimer/wiki/Connect-with-stackmat-like-hardware-timers

Note that last month (October 20) the connection was working.

I have been using an Android smartphone with cstimer_stackmat.apk installed as a replacement for the timer display and would appreciate it if you could make it available again.

**Comment by cs0x7f** [comment]
Fixed in https://github.com/cs0x7f/cstimer/commit/243003013e09c68a1cee73e5c730693309443849
