### ISSUE TITLE
Custom color scheme for scrambles display

### ISSUE THREAD

**Issue by tussosedan** [cs0x7f/cstimer#45]
Thanks so much for implementing all the various improvements lately! I've now switched back to cstimer, and it's great to be back.

This request is for myself and around 10% of the male population who are colorblind. Could we get a custom color scheme for the scrambles display? 

For example, on my cubes I use black instead of orange, and grey instead of green. I almost can't tell apart the green and orange on the scramble display.

**Comment by cs0x7f** [comment]
Done in https://github.com/cs0x7f/cstimer/commit/fb768a6f593a518308ecc3c91ef51eceef7c0a46

**Comment by tussosedan** [comment]
Works great, thanks a lot!
