### ISSUE TITLE
bug when switching sessions

### ISSUE THREAD

**Issue by spencerchubb** [cs0x7f/cstimer#451]
This issue is from a friend and I'm posting it on their behalf:

Sometimes when I'm switching sessions (with alt+up or alt+down keybinds) I get this weird bug where it shows my session 2 times (2x2) instead of the normal times, and if I enter in a time with this bug then it adds ~100 times from the session that I have to manually delete after, this is a problem with session 1 (3x3) mostly and maybe some others, here is a screenshot and does anyone know how to fix this

![image](https://github.com/user-attachments/assets/b32ab13b-d65e-4ece-9965-7a611938e008)

When the problem occurs I change sessions and then change back slowly and it goes away, but it gets annoying after quite a while

**Comment by OWelton-Rosie** [comment]
If anyone's curious, the Speedsolving Forms thread where the issue was first raised can be found at [https://www.speedsolving.com/threads/problem-with-cstimer.93868/](https://www.speedsolving.com/threads/problem-with-cstimer.93868/).

**Comment by cs0x7f** [comment]
Fixed in https://github.com/cs0x7f/cstimer/commit/56b1815080b24dd729df9a0063d28a38d6444b4e
