### ISSUE TITLE
Limit keys that trigger multiphase/timer stop

### ISSUE THREAD

**Issue by wilkojc** [cs0x7f/cstimer#452]
While using CsTimer with `entering times with: timer` setting after you start timing your solves with space, pressing any key on the keyboard (not sure if virtually any, but a lot of them work - function keys, brackets, letters etc.) will stop the timer or begin a new phase if using multiphase.

Is there a setting (or could it be implemented if not) that allows limiting the set of keys that stop the timer/multiphase? 

I sometimes need to alt tab during blind solving memo to look up a letter pair etc. and pressing alt causes a phase to end which is quite troublesome as I have to then start a new solve and add the times together.

**Comment by cs0x7f** [comment]
Implemented in https://github.com/cs0x7f/cstimer/commit/885c77235fc60be923ac38b9ce5e85630bf9dda8

**Comment by wilkojc** [comment]
Thank you! It works great
