### ISSUE TITLE
Scramble image not working (Opera gx)

### ISSUE THREAD

**Issue by Happygamer787** [cs0x7f/cstimer#453]
Scramble images don't show up for me on 2x2x2-7x7x7, pyraminx and skewb. They are visible for one frame when I reload the tab.
This only happens on opera gx, on microsoft edge it seemed to be working correctly.
![image](https://github.com/user-attachments/assets/b00054a5-4028-485f-aa39-1a06569b8352)

**Comment by cs0x7f** [comment]
Disable cstimer+
