### ISSUE TITLE
WCA 4x4 scrambles not random state

### ISSUE THREAD

**Issue by tussosedan** [cs0x7f/cstimer#46]
The WCA 4x4 scrambles on cstimer are not random state, although the WCA requires it for 4x4.

**Comment by cs0x7f** [comment]
Yes, random-state scramble is available but not by default, since it's too slow to obtain a scramble (several seconds on my laptop)

**Comment by tussosedan** [comment]
That's understandable, but still it shouldn't appear as "WCA" 4x4. Although you are caching the next scramble in localStorage, so in most cases it's instant. But if that's really a problem, maybe add a note in its name or something like that, otherwise it's misleading.

**Comment by tussosedan** [comment]
By the way, it's amazing that the 3x3 random state works so fast, ~20 ms on my laptop. Well done!

**Comment by cs0x7f** [comment]
Actually it's about 5ms on average on my laptop after fully initialization. When used in cstimer, it only does partial initialization and therefore the first several solvings will spend more time.
You can use scramble generator in tools to test it. On my laptop, it spends 5 seconds to generate 999 scrambles.
https://github.com/cs0x7f/min2phase.js

**Comment by tussosedan** [comment]
Hmm I did test it with 999 scrambles, and got 20 seconds, but now I'm really getting 5 seconds. Maybe the laptop was in power saving mode, no idea.

**Comment by tussosedan** [comment]
Hahaha I didn't know you're following reddit :) Giving users the choice is completely fine I think, but they just need to know that they have that choice -- and most users probably don't go through all the settings if they don't have to.

**Comment by cs0x7f** [comment]
Finally solved in  https://github.com/cs0x7f/cstimer/commit/096a5b3f39bcc598d4d09458d508e0eccbfd4a69
By keeping at least one scramble cached to improve scramble delay, and able to switch to random move scrambles by options.

**Comment by tussosedan** [comment]
Thank you!
