### ISSUE TITLE
Session-Specific Timer Input

### ISSUE THREAD

**Issue by Enigmagico** [cs0x7f/cstimer#50]
I have two separate sessions for 3x3 Blindfolded right now with two different timer inputs.

On the first session, where I time memo/exec splits, I use the regular "Timer" input. On the second, which I use for my stackmatted solves, I use the "Typing" input.

This leads me to the following request:

Being able to define, per session, how times are entered. This way I won't have to manually switch it every time I change sessions.

**Comment by Enigmagico** [comment]
On a related note, is there any chance for mobile stackmat support in the foreseeable future?

**Comment by topppits** [comment]
If you implement session-specific timer input, please make it optional. Sometimes I do a whole practise session with stackmat and another one just with keyboard.

**Comment by cs0x7f** [comment]
> is there any chance for mobile stackmat support in the foreseeable future?

Actually it's supported right now, but only works for specific mobile phone or with an external sound card, and with plenty of luck.

**Comment by cs0x7f** [comment]
Implemented in https://github.com/cs0x7f/cstimer/commit/0b8f66018b16086a00fd2235a6d11a1e02c51d19
