### ISSUE TITLE
Showing session name in confirmations

### ISSUE THREAD

**Issue by tussosedan** [cs0x7f/cstimer#51]
Please display the session name in confirmations -- this is especially relevant for using the new and awesome session manager, and especially on mobile. When I'm merging, splitting and deleting sessions, I'm never sure if I tapped the correct small link/icon, and it would be very helpful to know on which session the action is going to be performed.

**Comment by cs0x7f** [comment]
Done in https://github.com/cs0x7f/cstimer/commit/75d4b0525eea76f3656a983985030033584c41b8

**Comment by tussosedan** [comment]
Works great, and again you did it so fast! Thank you.
