### ISSUE TITLE
Megaminx Virtual not correctly recognising solved state

### ISSUE THREAD

**Issue by Mollerz** [cs0x7f/cstimer#52]
I messed up my PLL and so upon fixing my S2L it left me with 2 twisted corners on the LL, however the timer recognised it as solved and gave me a time.

**Comment by cs0x7f** [comment]
Thank you for the bug report. I'll fix it ASAP.

**Comment by cs0x7f** [comment]
Should be solved in https://github.com/cs0x7f/cstimer/commit/80cba703aefa812a0a183282b1f5f18e20ce2f2d
