### ISSUE TITLE
Giiker virtual cube not showing (after first refresh of website?)

### ISSUE THREAD

**Issue by HoshiYamazaki** [cs0x7f/cstimer#55]
As title says. Otherwise, csTimer is showing normal timer.
Tested on chrome under Windows 10 and Android.
![image](https://user-images.githubusercontent.com/21007545/50521433-fb274280-0ac5-11e9-9de2-cb09ad4f1eed.png)
![image](https://user-images.githubusercontent.com/21007545/50521444-05494100-0ac6-11e9-8e3a-c2a221f8bdf9.png)
![image](https://user-images.githubusercontent.com/21007545/50521457-1a25d480-0ac6-11e9-9387-e9860ade2531.png)

**Comment by HoshiYamazaki** [comment]
Yes.

**Comment by cs0x7f** [comment]
Should fixed in https://github.com/cs0x7f/cstimer/commit/f4f326d8448f28789017049f0bd03ce6b25e610e
