### ISSUE TITLE
Export to CSV doesn't work on Safari

### ISSUE THREAD

**Issue by dsoegijono** [cs0x7f/cstimer#58]
Actually, I can't seem to export to CSV on Safari. Clicking on the button, it attempts to open the blob in a new tab but it doesn't download/render. Confirmed it works on Firefox and Chrome.

~~Is it possible to export to file (TXT or CSV), but only the specific session I'm on. I see that it currently have exporting AoX to CSV, so something like that but for the entire session. Thanks!~~

☝️ Just figured out how this works, clicking on the overall solves/mean area, but I don't think that's very intuitive. Maybe from the Session Manager, we can have another option which is to export it?

**Comment by cs0x7f** [comment]
1) Since I do not have a mac book, I have no idea how to reproduce and debug the problem.
2) Good suggestions. The question is that there are too many data to be shown in session manager but the width of each row is limited. I'm trying to do tradeoff or find some other ways to show data.

**Comment by dsoegijono** [comment]
1. I'll try to see if I can figure it out 😀
2. How about on Data Import/Export, add another button "Export session to CSV"?

**Comment by cs0x7f** [comment]
In https://github.com/cs0x7f/cstimer/commit/53469b1ef5f52a1806d064f1299387f10484fcdc, I add another button in session manager to download csv file for any session.
