### ISSUE TITLE
[Suggestion] Consistency Tool

### ISSUE THREAD

**Issue by Mollerz** [cs0x7f/cstimer#61]
I like to play this "game" when I do practice to help my consistency. I will give an example:

I average about 12 seconds for 3x3, so I decide that I would like all of my solves to be under 12.5 seconds to help with my consistency. So what I do is I do practice solves, and every solve in a row under 12.5 second I add one. I try and get this number as high as possible, and if I get a solve over that time it resets back down to 0. It would be really cool if there was a tool where you could track how many of your solves are sub-x in a row.

What do you think?

**Comment by cs0x7f** [comment]
Seems similar to the 'time distribution' tool. The only difference is to show accumulated counts instead of per time-interval counts.

**Comment by Mollerz** [comment]
It would be quite similar yes, it could show your most sub-x in a row for a few intervals that are automatically calculated.

**Comment by cs0x7f** [comment]
In the new time distribution tools after https://github.com/cs0x7f/cstimer/commit/b60e54fe2e88cb4e39166354908bb5f88c4fa579,  "<t x/y" means there are totally y values sub t, and x values continuously till the last one.

**Comment by xsrvmy** [comment]
Further request (probably should be an option in settings): Show the PB for sub-xs in a row as well

**Comment by cs0x7f** [comment]
Sorry, what does it mean by 'PB for sub-x'?

**Comment by xsrvmy** [comment]
The most number of sub-Xs in a row in the entire session

**Comment by cs0x7f** [comment]
I get it. I'm thinking about how to display these results, since 'x/y' has already confused many people.
