### ISSUE TITLE
[Suggestion] Data export/import

### ISSUE THREAD

**Issue by Berkmann18** [cs0x7f/cstimer#62]
At the moment, using this timer on HTTP/HTTPS or from a browser to another on the same machine leads in not having the sessions synchronised which makes it tricky in situations like:
- having a big session on the HTTP-based domain but wanting to use the HTTPS without losing anything,
- changing browsers.

**Comment by cs0x7f** [comment]
The data export/import function can be opened by click the second button in the left-top panel.
You are able to either import/export all your data to/from a local file or cstimer's server or google storage.

**Comment by Berkmann18** [comment]
Ah, I see, the button don't communicate that it also does import but only export.

Not sure if you're aware of it but the "Login using Google account" button leads to an invalid OAuth URL:
Error 400 (OAuth2 Error)!!
>
> 400. That’s an error.
>
> Error: redirect_uri_mismatch
>
> The redirect URI in the request, http://www.cstimer.net/timer.php, does not match the ones authorized for the OAuth client. To update the authorized redirect URIs, visit: https://console.developers.google.com/apis/credentials/oauthclient/738060786798-octf9tngnn8ibd6kau587k34au263485.apps.googleusercontent.com?project=738060786798

I also get an error when I try the "Login using WCA account" which shows:
> An error has occured
> `The requested redirect uri is malformed or doesn't match client redirect URI.`

**Comment by cs0x7f** [comment]
Well, you should use   https://cstimer.net/   instead of http ones

**Comment by Berkmann18** [comment]
@cs0x7f Indeed, good thing those errors aren't problematic when using HTTPS.
Not related but have you thought about making a duel/challenge feature or something that allows people to see leaderboards (although compared to other services which do either, the sessions types aren't fixed)?
