### ISSUE TITLE
Bug in time distribution

### ISSUE THREAD

**Issue by OriEy** [cs0x7f/cstimer#63]
![bug](https://user-images.githubusercontent.com/20462241/50901056-5ab31580-1417-11e9-82a9-89132cf8b936.png)

This seems wrong, shouldn't it be 2/2 for all the 3/2s?

**Comment by cs0x7f** [comment]
Should fixed in https://github.com/cs0x7f/cstimer/commit/dfc335d9410c1cbe55efc388d7fb15095a516e91
