### ISSUE TITLE
Line breaks in CSV

### ISSUE THREAD

**Issue by tussosedan** [cs0x7f/cstimer#64]
Mega scrambles (and possibly others?) generate line breaks in the CSV -- which breaks parsing.

Example:
No.;Time;Comment;Scramble;Date;P.1
1;1.22;;  R-- D++ R++ D-- R++ D-- R++ D++ R++ D-- U'
  R-- D++ R++ D-- R++ D++ R++ D-- R++ D++ U
  R++ D-- R-- D++ R-- D-- R++ D-- R-- D++ U
  R-- D-- R++ D-- R++ D++ R++ D++ R++ D++ U
  R-- D-- R++ D++ R-- D-- R++ D++ R++ D-- U'
  R++ D-- R++ D-- R++ D-- R++ D-- R-- D-- U'
  R++ D++ R-- D++ R++ D++ R++ D-- R-- D-- U';2019-01-11 09:27:00;1.22
2;0.86;;  R++ D-- R++ D-- R++ D-- R-- D-- R++ D-- U'
  R++ D++ R-- D-- R++ D++ R-- D-- R++ D++ U
  R-- D-- R++ D-- R-- D++ R-- D++ R++ D-- U'
  R++ D++ R++ D-- R++ D++ R++ D-- R++ D++ U
  R++ D-- R-- D++ R-- D++ R++ D++ R++ D-- U'
  R++ D++ R-- D++ R++ D-- R-- D++ R++ D++ U
  R++ D-- R-- D-- R++ D-- R-- D-- R-- D-- U';2019-01-11 09:27:02;0.86
3;1.19;;  R++ D++ R++ D-- R++ D-- R-- D++ R++ D++ U
  R-- D-- R-- D++ R-- D++ R++ D++ R-- D++ U
  R++ D-- R-- D++ R++ D-- R++ D-- R++ D++ U
  R++ D++ R-- D-- R-- D-- R-- D++ R++ D-- U'
  R-- D-- R-- D-- R++ D-- R-- D-- R-- D++ U
  R-- D-- R-- D-- R++ D-- R-- D++ R++ D++ U
  R-- D++ R++ D++ R++ D-- R-- D-- R-- D-- U';2019-01-11 09:27:03;1.19

**Comment by cs0x7f** [comment]
Does it break parsing by cstimer, or break parsing by some other tools, e.g. microsoft excel or some other csv processing package?
According to RFC 4180 standard (who defines csv format), it is legal to use line-break in a field, if the field is quoted correctly.

**Comment by tussosedan** [comment]
Whoops I pasted the wrong CSV from another timer. Now fixed to show cstimer's CSV -- which isn't quoted.

**Comment by cs0x7f** [comment]
Should fixed in https://github.com/cs0x7f/cstimer/commit/ababebc706807b6e1f239f8368ba38b0aa87edb7
