### ISSUE TITLE
Export to server (csTimer) doesn't seem to work anymore

### ISSUE THREAD

**Issue by topppits** [cs0x7f/cstimer#65]
Clicking the Export to server (csTimer)-button doesn't seem to do anything right now, even after waiting for a couple minutes. No confirmation that it was uploaded nor an error message or anything.

Importing from server gives me an old version, which seems to confirm that the export doesn't work right now.

**Comment by cs0x7f** [comment]
main version or /new/ version?

**Comment by topppits** [comment]
Weird. I just tried it again with the normal and the /new/ version on Opera beta and on Chrome and it won't work. Deleting cookies didn't change anything. Import works fine.

**Comment by cs0x7f** [comment]
Sounds impossible. I have not modified the main version in the past 3 days. Is there any error log in the console?

**Comment by topppits** [comment]
POST https://cstimer.net/userdata.php 413 (Request Entity Too Large)

**Comment by cs0x7f** [comment]
Should fixed.
