### ISSUE TITLE
Import solves from other timers

### ISSUE THREAD

**Issue by cs0x7f** [cs0x7f/cstimer#66]
I'm going to enable csTimer to import solves from other timers. The function button is at  Export -> Import session(s) from other timers.
With this function, you are able to not only import solves from other timers, but also import solves from cstimer itself without overwrite your local solves.

Currently supported timers:
- [x] csTimer (included exported csv)
- [x] Block Keeper
- [x] Twisty Timer
- [x] Cube Timer (Android)
- [x] DCTimer

If you want to import solves from other timers, leave a comment in this issue and send an exported file to me (cs0x7f@gmail.com).
Also, importing from the supported timers are not well tested. If you find some files that cannot be correctly imported, just leave a message and send the file to me.

**Comment by ddombrowsky** [comment]
Just a quick note unless anyone happens upon this:

`cstimer` will successfully import the _backups_ from Twisty Timer.  Twisty has an "export to other timers" function, which produces a file that does not appear to import into `cstimer`.  

The file that _does_ work is formatted like this:
```
Puzzle,Category,Time(millis),Date(millis),Scramble,Penalty,Comment
"333";"Normal";"122170";"1609701323544";"L2 R2 F2 L2 F' L2 D2 B L2 R B L' R2 D' L' U' L' R2 D'";"0";""
"333";"Normal";"156540";"1609703651758";"F' U2 F' U2 L2 U2 R2 F' R2 B' F U' R' D2 F' R' B2 U B L' U2";"0";""
```

**Comment by lapo-luchini** [comment]
CSV export from [Cube Solver (Android)](https://play.google.com/store/apps/details?id=com.jeffprod.cubesolver): [rubik.csv](https://github.com/cs0x7f/cstimer/files/7818019/rubik.csv)
