### ISSUE TITLE
Controls for virtual cube should be independent of keyboard layout

### ISSUE THREAD

**Issue by torchlight** [cs0x7f/cstimer#72]
Rather than event.keyCode, [event.code](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/code) should be used.

Currently, the controls for non-qwerty keyboard layouts are all over the place (e.g. the keys for U, R and R' moves ("J", "I" and "K") are on the left side of a Dvorak layout), which makes the virtual cube almost unusable without changing the keyboard layout first.

**Comment by bugybunny** [comment]
Never used it but thanks from someone else that uses a rather exotic layout (NEO) :) I agree.
