### ISSUE TITLE
Pyra scrambles have 2 spaces between tips

### ISSUE THREAD

**Issue by bugybunny** [cs0x7f/cstimer#73]
U R' B' R' B' U L R' l  b'  u for example. Is that on purpose or not intended? Looks strange and not pleasing to the eye.

![image](https://user-images.githubusercontent.com/5311105/54160303-75bdf800-444f-11e9-998a-66aba178a431.png)

**Comment by cs0x7f** [comment]
Fixed in https://github.com/cs0x7f/cstimer/commit/6445356276dbaa74e887823e230a894a252e0326
