### ISSUE TITLE
Language resets to system language

### ISSUE THREAD

**Issue by viktorzenk** [cs0x7f/cstimer#78]
After the latest update cstimer automatically sets its language to my system language (Swedish). I can change it back to English in the settings, but it only seems to store that setting in the URL (?lang=en-us), so the next time it's back to Swedish.

Would it be possible to store the language setting in a more permanent way?

**Comment by cs0x7f** [comment]
Fixed in https://github.com/cs0x7f/cstimer/commit/105ddf6690910506ec76ecd35671a07b47bb80a7
I use cookie to store the language information as well.

**Comment by bugybunny** [comment]
Thanks for opening this and for (almost?) fixing. This was also bugging me a lot.

**Comment by cs0x7f** [comment]
> Thanks for opening this and for (almost?) fixing. This was also bugging me a lot.

The bug should be fixed in https://cstimer.net/new/
And will be updated to the main version in the next few days.
