### ISSUE TITLE
5 x 5 x 5 visualization possibly wrong

### ISSUE THREAD

**Issue by canibanoglu** [cs0x7f/cstimer#79]
Hello,

I've been working on a cubing project and I've been using cstimer as a correctness checking tool (and for lots of erm... "inspiration"). I've noticed something weird with the 5 x 5 visualization though. What's shown is different than what I see and as a final check I tried applying the same scramble myself and it does look like there is something funky going somewhere.

It is possible that I'm parsing the scramble wrong (that is, my knowledge of the moves are wrong and I'm doing a wrong move somewhere) but I don't think so.

Here is the scramble string 
```U2 Lw2 F2 Uw2 D Rw2 B D' R' B R2 Rw2 Dw2 D Lw Fw2 Uw' U2 B Uw2 D Fw Rw Lw' U' Lw Dw' R' B2 Uw F2 Bw2 Uw L' Uw' L2 Uw' Rw2 Fw2 Bw'```

Here's the visual from `cstimer`:

![cstimer5](https://user-images.githubusercontent.com/3527191/56774598-b2f20580-67c3-11e9-9a38-79b2055004f9.JPG)

Here's what I have:
![my5](https://user-images.githubusercontent.com/3527191/56774610-beddc780-67c3-11e9-984b-cd418f10b42c.JPG)

**Comment by canibanoglu** [comment]
I didn't check the code on this repo but if you need help with this I'd be glad to lend a hand

**Comment by cs0x7f** [comment]
I use "input scrambles" to load your scramble, and the scramble image is the same as the second picture you post. 
A possible cause is that, you only copyed a part of a 5x5x5 scramble, since the length of the scramble you post is only 40 moves. Actually, the length of a typical 5x5x5 scramble should be 60 moves for WCA competition.

**Comment by canibanoglu** [comment]
Hmm you're right, it was due to the scramble area scrolling. I think it deserves a separate issue though because the app layout is acting weirdly on high resolutions.
