### ISSUE TITLE
Timer is incorrectly rounding instead of truncating in certain places

### ISSUE THREAD

**Issue by xsrvmy** [cs0x7f/cstimer#8]
The following is an incorrect output that was generated when my friend used the timer:
```
Generated By csTimer on 2017-6-27
single: 1:00.00

Time List:
1. 59.99  (mega scramble)
```
The time was 59.997 with the millisecond option on. Notice that the single is incorrectly displayed.

This also goes into calculating averages. The times should be truncated first before calculating the average, like on competition.
For example, five 1.009s gives a 1.009 average in millisecond mode. That is fine. However, the same times in centisecond mode count as 1.00s, but the timer shows a 1.01 average. The times should be truncated first before the average is calculated.

**Comment by cs0x7f** [comment]
Fixed in https://github.com/cs0x7f/cstimer/commit/53e95c89717a768450233915deca021a403c95ce
