### ISSUE TITLE
[Planning/documentation/help request] Abstracting logic into npm modules

### ISSUE THREAD

**Issue by canibanoglu** [cs0x7f/cstimer#82]
Hello,

As I've mentioned on another issue I've been working on a cubing resource app for myself and I find myself looking at cstimer very often for ideas and implementation details. As far as I can tell cstimer contains the most tools about cubing. I notice that most of the functionality that I implement in one way or another ends up producing something very similar to what is already here and I think it would be in community's best interest to abstract away these tools and libraries within cstimer to separate npm modules to make it more accessible to other developers.

I've been reading the code a lot lately and I'm under the impression that some of the libraries and tools are generated JS code (mainly due to interesting ways of initializing variables, in ways I don't imagine a human would). But I can't find what the real source codes for these. I would appreciate it immensely if you could point me in the right direction.

Which brings me to another request for help. I imagine creating npm modules for all of these functionalities will involve more than translating and abstracting code and that I should actually understand what's happening in the code. The thing is the code is not really understandable for me and I was wondering where I should look to get a general idea for the approaches used in these libraries. I am aware of Kociemba's site but haven't gone through it yet, is that enough to give me a good understanding or should I look elsewhere for the mathematical foundation as well? For example I would like to understand how the cross solver works exactly.

I didn't know how else to contact you about these questions so I'm opening an issue. I apologize in advance if there was a better way to contact you and I missed it.

**Comment by cs0x7f** [comment]
Some of the codes of solvers (3x3x3, 4x4x4, sq1) are converted from their java versions by gwt.

Most of solvers (cross, eoline, 2x2x2, etc) in cstimer use IDA* algorithm to solve the cube/stage. 
Jaap has written an article to introduce how it works. https://www.jaapsch.net/puzzles/compcube.htm

**Comment by canibanoglu** [comment]
Thank you very much!

**Comment by jquense** [comment]
@canibanoglu you still interested/working on this? I'd be interested in helping perhaps. I'm also enjoying building out my own bespoke cubing utils and apps (just for myself) and given that cstimer is the defacto standard it'd be great if a lot more of the core code was more portable or consumable as libraries.

I do also have some questions, unclear where the best place to ask them is. But mainly wondering why cross compile min2phase, vs using something more native or simpler? I'd imagine it's all still very fast, but unclear how much more compared to some of the existing 2 phase algorithm JS solvers. I guess even more generally what is the main benefit to using a solver for generating scrambles vs doing something more naive?
