### ISSUE TITLE
356i sync issues

### ISSUE THREAD

**Issue by gekkoe** [cs0x7f/cstimer#83]
Once I'm able to get my 356i to sync with the app (often takes several reloads of the page for some reason) I'm then able to get a single scramble and solve to work.

After the first solve though, the virtual cube stops responding to my cube. If there's some sort of reset button I need to push or some such I haven't been able to find one that works.

Thanks a ton for getting this programmed in so fast though! I'd much rather use your excellent app than the native one that Gan put out. (I'm a Roux solver so....)

**Comment by cs0x7f** [comment]
Is there any bug reported in the console (Opened by pressing F12)

**Comment by gekkoe** [comment]
I'll be happy to let you know, if I can just figure out how to get a keyboard to show up while viewing your page on my phone.

**Comment by cs0x7f** [comment]
> 
> 
> Sorry haven't done any phone dev, though I am a software engineer and will be happy to help if I'm able. I've been trying to figure out how to get a keyboard to show up while viewing your page on my phone, or some other way to open the debug console. I did finally get the keyboard up, by clicking on a time recorded in a session and clicking the comment text box, but when I then hit the F12 key nothing seems to happen.

Well, I have never use smartphone to connect with gan356i. Are you able to use a laptop with bluetooth to connect with gan356i and reproduce the bug?

**Comment by gekkoe** [comment]
Unfortunately I don't have access to a laptop with bluetooth. I only use it on a Samsung S8+ Android phone. If I can be of any assistance getting it to work properly on such devices though, I'll be happy to help.

**Comment by HoshiYamazaki** [comment]
![image](https://user-images.githubusercontent.com/21007545/65457336-a2fe5080-de4b-11e9-947d-ad87ae8174d3.png)

I have the same issue, chinese Gan 356i.

**Comment by cs0x7f** [comment]
> ![image](https://user-images.githubusercontent.com/21007545/65457336-a2fe5080-de4b-11e9-947d-ad87ae8174d3.png)
> 
> I have the same issue, chinese Gan 356i.

Try https://cstimer.net/src/?debug=1

Is there any log starts with [gancube]?

**Comment by peisenh** [comment]
Same here. Really often in the solves the cube is no longer responding. See attached image with debug infos.
![Bildschirmfoto_2020-07-01_18-51-59](https://user-images.githubusercontent.com/58936244/86271098-9a9e2780-bbcc-11ea-8f5e-7c06da34f3f0.png)
