### ISSUE TITLE
New solves don't show until reload

### ISSUE THREAD

**Issue by topppits** [cs0x7f/cstimer#84]
Weird little bug I just experienced and I can replicate it.

I was timing a solve on https://cstimer.net/new/.
I had 2 tools, though they were hidden. The right tool was Daily Statistics and on the left draw scramble. Scramble was hidden as well, only the scramble list was visible.
Those were the settings from the previous session, I did the solve and when I finished, it didn't show in the time list. When you show tools and do another solve, now the new time shows and with the correct number, but the previous one doesn't. So if the session was previously empty and you only did those two solves, it'd look like [this](https://i.imgur.com/kgCSTB4.png). Reload the page or close and reopen and both solves are there. Reloading before you have a new solve that is visible will result in losing the solve.

So to replicate it, hide the tools and scramble, close the tab, open cstimer again, do a solve.

**Comment by cs0x7f** [comment]
Fixed in https://github.com/cs0x7f/cstimer/commit/4eafa74ddee67f9bf16f45f2ef020604b9c95f37

**Comment by bugybunny** [comment]
Sorry to hijack this issue but how can I have more than one tool open?

**Comment by topppits** [comment]
option -> tools -> number of tools

:D

**Comment by bugybunny** [comment]
Oh wow, this is awesome :) Thanks a lot. I guess there is so much about csTimer that most users will never see (mostly the new stuff).
