### ISSUE TITLE
Session order changes spontaneously

### ISSUE THREAD

**Issue by tussosedan** [cs0x7f/cstimer#86]
This happens sometimes, here's an export with an example. The smaller 3x3 2H session with 79 solves is currently session 2, but after closing cstimer and reopening it it becomes session 3, and then session 4 and so on. 

[cstimer_20190601_131834.txt](https://github.com/cs0x7f/cstimer/files/3243669/cstimer_20190601_131834.txt)

**Comment by cs0x7f** [comment]
Fixed in https://github.com/cs0x7f/cstimer/commit/d0ef31ae9de37afa34ccecdabe450e33d3c308cd

**Comment by tussosedan** [comment]
Yay, thank you!
