### ISSUE TITLE
4BLD scramble needs some love

### ISSUE THREAD

**Issue by topppits** [cs0x7f/cstimer#89]
I just got this scramble:
![image](https://user-images.githubusercontent.com/45535675/61556933-376ec000-aa63-11e9-85ba-cf18a0d8d74b.png)

Second row in the middle: Fw2 Fw'

**Comment by topppits** [comment]
Does the setting "Using fast scramble for 4x4x4 (non-official)" also work for 4BLD scrambles or are those always random moves/random state and if so which one?

**Comment by zeecho** [comment]
Hi, 

I also ran into this while using the "WCA 4x4x4" scramble mode :
![2021-03-04-114442_1638x125_scrot](https://user-images.githubusercontent.com/5508488/109955921-53c87a80-7ce3-11eb-8360-181c9f964526.png)

It's the first time it has happened to me though (I've practised 4x4 with cstimer for a few years now)
