### ISSUE TITLE
Giiker cube won’t connect to my laptop

### ISSUE THREAD

**Issue by CamzyWE** [cs0x7f/cstimer#91]
When I try and connect my cube to cstimer.net nothing happens when I click connect and when I click connect on avaver.github.io it says NotFoundError: Bluetooth adapter not available I have enabled the chrome flag: Experimental Web Platform Features. Bluetooth definitely works on my laptop as I use my joycons as game controllers using Bluetooth. Is there a fix?

**Comment by cs0x7f** [comment]
Open  chrome://bluetooth-internals/#devices  and check whether your cube can be detected by your browser.

**Comment by CamzyWE** [comment]
Thank you for your reply, yes it can be discovered when I click start scan. I noticed an adapter section as well and the only thing that is green is initialized.
