### ISSUE TITLE
Any update to support Giiker i3SE

### ISSUE THREAD

**Issue by caichunjian520** [cs0x7f/cstimer#92]
Giiker i3SE bluetooth data is totally different from i3 or i3S. So can't decode data to get all colors information.

**Comment by caichunjian520** [comment]
I also bought an i3S cube from Giiker yesterday, find that, the data also been changed from old cubes.

**Comment by cs0x7f** [comment]
> 
> 
> I also bought an i3S cube from Giiker yesterday, find that, the data also been changed from old cubes.

Is there any firmware update on all i3S sold or just a new version of i3S?

**Comment by caichunjian520** [comment]
I think Giiker company just update new version of i3S as well as the new cube i3SE(special edition). I tested on i3S(produced in July 2019) and i3SE, both not work. But i3(produced in April 2019) works fine.

You can hear different sound from old version. Charge, connect, disconnect are totally different, but the new version only has a short "Dee" sound compared to old version. I am pretty sure that this is not caused by software update.

So as far as I am concerned, Giiker encrypted their bluetooth data recently(this two months). So if someone purchased the latest cube, it won't work with bluetooth web apps on Github.

For example:
In solved condition
the old ble data: 0x1234567833333333123456789abc000043414341

new ble data:
can be this: 0x843a3f4e743e77c8f4869801ab804bdbf617a782
or can be this: 0xda6d6a39fc105890d5def0a1494ba457756da7a7
or can be others

**Comment by cs0x7f** [comment]
I have already found the encryption algorithm and decryption algorithm. However, since I do not have a physical Giiker cube myself, it's not possible for me to check whether the decryption algorithm works as expected.

**Comment by caichunjian520** [comment]
I can test it for you.

**Comment by cs0x7f** [comment]
Try  https://cstimer.net/src/

**Comment by caichunjian520** [comment]
I will test it within 10 hours.

**Comment by caichunjian520** [comment]
I tested, It works like a dream, perfectly correct.
