### ISSUE TITLE
 session-related statistics options

### ISSUE THREAD

**Issue by topppits** [cs0x7f/cstimer#94]
"Statistical indicators" custom for every session aren't consistent:

I set my typically sighted sessions as mo3, ao5/12/50/100/1000.
For 3BLD mo3, ao5/12/25, 4BLD mo3, ao5/12 and MBLD only mo3 (can't put nothing there..)

Going trough the sessions it's just all over the place, changing seemingly randomly: https://i.imgur.com/GKxnWLQ.gifv

Same goes for those stats: https://i.imgur.com/FcyNKri.png

**Comment by cs0x7f** [comment]
Should be fixed in https://github.com/cs0x7f/cstimer/commit/46ef0625d2f7872f8d976340237863119d6fb837
