### ISSUE TITLE
Prevent inspection start when stackmat timer is not reset

### ISSUE THREAD

**Issue by dominik-korsa** [cs0x7f/cstimer#95]
I'm using the **YuXin Timer v2**. It doesn't seem to support starting the inspection by touching the sensors, so I start the inspection manually (using the spacebar). That means I have a tendency to forget to reset the timer.
My idea is, that pressing the spacebar to start the inspection wouldn't start when the timer is not reset.

**Comment by cs0x7f** [comment]
Fixed in https://github.com/cs0x7f/cstimer/commit/7071c434d27caa1c6df0983c9b09ef5f277b4e44

**Comment by dominik-korsa** [comment]
Works in https://cstimer.net/src/ 👍

**Comment by tussosedan** [comment]
Jumping in on this, can inspection be supported for the yuxin timer?

**Comment by bugybunny** [comment]
TIL that I can start the inspection with my timer. I just knew about spacebar and so forgot to reset my timer sometimes so I'm also happy with this change :)

**Comment by cs0x7f** [comment]
> Jumping in on this, can inspection be supported for the yuxin timer?
The head signal of yuxin timer is identical forever. So it's impossible to know whether left/right hand is on the pad.
