### ISSUE TITLE
Feature request: Have typing entry work as in Cubecomps

### ISSUE THREAD

**Issue by viktorzenk** [cs0x7f/cstimer#96]
In Cubecomps, you don't have to enter the periods or colons when entering times.
534 will simply be entered as 5.34, and 61843 as 6:18.43, and so on.

I would love to see this feature in csTimer, perhaps as an optional setting if everyone doesn't like it.

**Comment by cs0x7f** [comment]
Option->timer->Unit when entering an integer->centisecond.
However, it will treat 61843 as 618.43 (which is 10:18.43) right now. 
After https://github.com/cs0x7f/cstimer/commit/07df1bb069b1473efbde5dc4d06b72fd9abae206, you are able to determine what 61843 means, 6:18.43 or 618.43, etc

**Comment by viktorzenk** [comment]
Awesome, thank you!
