### ISSUE TITLE
[Bug] Cross-session stats broken

### ISSUE THREAD

**Issue by tussosedan** [cs0x7f/cstimer#97]
It works after merging sessions with the same names, but that defeats the purpose :)

[cstimer_20190829_090524.txt](https://github.com/cs0x7f/cstimer/files/3554905/cstimer_20190829_090524.txt)

![image](https://user-images.githubusercontent.com/32999689/63929598-614fd500-ca5a-11e9-81b6-883ea6e9d883.png)

**Comment by cs0x7f** [comment]
The bug cannot be reproduced in /new/ , seems be fixed several commits ago.

**Comment by tussosedan** [comment]
Confirmed, does not happen on /new. Thanks!
