### ISSUE TITLE
new Gan356i firmware?

### ISSUE THREAD

**Issue by boogie** [cs0x7f/cstimer#99]
Hi,

I've tried the Gan356i cube support, but it is not working for me. Maybe I have a cube with a new firmware? I've debugged what the cube is sending, and it seems to be quite random for some characteristics.

For example, if I'm polling the ```fff7``` characteristic for a solved cube, it sends this ```b9bb56bfff7c7808ad3fa56bca1617707c06```. For ```fff6```, it sends ```8a7763e38ca59c697f941d1feb6decd9f01cdd```. For ```fff5```, it sends these when I'm polling (in about 5 secs, while nothing is happening, cube is in my bag):

```
[
    "07f69e01542848b5a7636853a5702b4f9639eb",
    "07f69e01542848b5a7636853a5702b4f9639eb",
    "fa403ff691b5df9f55f16e7526ad2b258fb519",
    "fa403ff691b5df9f55f16e7526ad2b258fb519",
    "d973447f4dafe637a0d37b7fa4e87df85e0a44",
    "d973447f4dafe637a0d37b7fa4e87df85e0a44",
    "fc3aa60338ea7f33765977d0de99af0cdb1d24",
    "5a1bbc8efbc0d57713289c1137f6244c52d4d4",
    "5a1bbc8efbc0d57713289c1137f6244c52d4d4",
    "5a1bbc8efbc0d57713289c1137f6244c52d4d4",
    "ad2a039af51e19101fbb0f43f9ebd96a14fbae",
    "6ba6279cab20496cc575034f39ca6950c7fb9b",
    "6ba6279cab20496cc575034f39ca6950c7fb9b",
    "c9aeb9d0cf150cebdc628c18fea7f0658e285c",
    "c9aeb9d0cf150cebdc628c18fea7f0658e285c",
    "c9aeb9d0cf150cebdc628c18fea7f0658e285c",
    "4d0506a36b1ad9275360820632a66b922e7866",
    "e98379434e8661a01074a775821b12258b62b6",
    "e98379434e8661a01074a775821b12258b62b6",
    "6a997a46bd88b1863a9b1a3e8fd499b8b031c7",
    "6a997a46bd88b1863a9b1a3e8fd499b8b031c7",
    "bf5b34f64f96c84cda43547b1487881cbcd219",
    "bf5b34f64f96c84cda43547b1487881cbcd219",
    "152826e127aa9d5dc32e81f9915baf9ee326af",
    "152826e127aa9d5dc32e81f9915baf9ee326af",
    "5913c8f675bef9f2df992d17e8deccbac65127",
    "5913c8f675bef9f2df992d17e8deccbac65127",
    "5913c8f675bef9f2df992d17e8deccbac65127",
    "1a8f1e8b0f35655bff77f73e5857d5d73059b7",
    "1a8f1e8b0f35655bff77f73e5857d5d73059b7",
    "418441b957bb959820bd86ea45bb1570231e9d",
    "7a452b4999f54e659d0e67b0dde3872f6c6acb",
    "7a452b4999f54e659d0e67b0dde3872f6c6acb",
    "7a452b4999f54e659d0e67b0dde3872f6c6acb",
    "7a452b4999f54e659d0e67b0dde3872f6c6acb",
    "e41fe8f39a608a7beb1ce08697fa21078f6157",
    "e41fe8f39a608a7beb1ce08697fa21078f6157",
    "01ba9928b948b4f57072a13ae78bc582eb48c0",
    "01ba9928b948b4f57072a13ae78bc582eb48c0",
    "1515add66f346cbd3f9239d470ee35245077e1",
    "1515add66f346cbd3f9239d470ee35245077e1",
    "02777da1c4fae628838d95b34392d1fef82875",
    "02777da1c4fae628838d95b34392d1fef82875",
    "21155f4f27427b472ef771152f6afa4d6a4405",
    "5a734f072ebda3556969a42cdc6f0cb038e9ec",
    "5a734f072ebda3556969a42cdc6f0cb038e9ec",
    "5a734f072ebda3556969a42cdc6f0cb038e9ec",
    "14c0e1324f6855d58a0fa82cf093aa5879b2c0",
    "14c0e1324f6855d58a0fa82cf093aa5879b2c0",
    "14c0e1324f6855d58a0fa82cf093aa5879b2c0",
    "14c0e1324f6855d58a0fa82cf093aa5879b2c0",
    "e1ce596164112b00d15c1dd1d1f54ae6469def",
    "e1ce596164112b00d15c1dd1d1f54ae6469def",
    "b4a07d41904abb1e1f261ae1eac5e3c5947808",
    "5e6a69aeffb91f6bc22a5c51f0955c3120459c",
    "5e6a69aeffb91f6bc22a5c51f0955c3120459c",
    "5e6a69aeffb91f6bc22a5c51f0955c3120459c",
    "a983d5664610518b863356fcbdd2e127793d68",
    "a983d5664610518b863356fcbdd2e127793d68",
    "f1caec217d7d9ecedb6ca8774a534af90a461c",
    "f1caec217d7d9ecedb6ca8774a534af90a461c",
    "2e43f7660f4082fe37b8a094d0ecfa42ac9abd",
    "2e43f7660f4082fe37b8a094d0ecfa42ac9abd",
    "2e43f7660f4082fe37b8a094d0ecfa42ac9abd",
    "d3f1fd4a6375aab8fe25974851155b98882af9",
    "d3f1fd4a6375aab8fe25974851155b98882af9",
    "09c8f207bb532129e0e244f28f634e8465e451",
    "09c8f207bb532129e0e244f28f634e8465e451",
    "68b7f8c75a0b485448d1f7b217a2b133e78b31",
    "68b7f8c75a0b485448d1f7b217a2b133e78b31",
    "68b7f8c75a0b485448d1f7b217a2b133e78b31",
    "73407ef5e797980ef4b76fc90e40cb0180489c",
    "73407ef5e797980ef4b76fc90e40cb0180489c",
    "ad0aa346190d8ee889a790e2c24bcbd526296a",
    "ad0aa346190d8ee889a790e2c24bcbd526296a",
    "5473aa2ef27bf169a62ceb8bfdd273ca3507c9",
    "5473aa2ef27bf169a62ceb8bfdd273ca3507c9",
    "5473aa2ef27bf169a62ceb8bfdd273ca3507c9",
    "9e263ad8f8f474a063e6c7bef9b032e39c0883",
    "9e263ad8f8f474a063e6c7bef9b032e39c0883",
    "5eda86308b876ab650fda0ba1b84ef6081b98a",
    "5eda86308b876ab650fda0ba1b84ef6081b98a",
    "b2d77a0c803ac4b975dcfeabf891d4884f58de",
    "b2d77a0c803ac4b975dcfeabf891d4884f58de",
    "b2d77a0c803ac4b975dcfeabf891d4884f58de",
    "7a043502d7eccd3c19099426e0ca77274f634b",
    "7a043502d7eccd3c19099426e0ca77274f634b",
    "7a043502d7eccd3c19099426e0ca77274f634b",
    "37de3fe790271b795571274008280ed2356ada",
    "37de3fe790271b795571274008280ed2356ada",
    "264daca5e182b45c752f2d3b3452079a6ad9f2",
    "7a3adcf7614ade72ba9734662f13c98d5f02d4",
    "7a3adcf7614ade72ba9734662f13c98d5f02d4",
    "7a3adcf7614ade72ba9734662f13c98d5f02d4",
    "7a3adcf7614ade72ba9734662f13c98d5f02d4",
    "81530f44f25a36f9217e90e002679c392e61af",
    "81530f44f25a36f9217e90e002679c392e61af",
    "81530f44f25a36f9217e90e002679c392e61af",
    "ac48b82b0c164e3261b8c3d53c57ede868f511",
    "ac48b82b0c164e3261b8c3d53c57ede868f511"
]
```

I'm getting a different set of values for ```fff5``` if I'm doing a move on the cube, and similar values to this if I'm moving it back. I see no patterns at all. For a solved cube there are new values coming later (maybe it is a time based encoding), and old values are not repeated anymore.

Do you have any idea about how I should decode these?

Andras

**Comment by cs0x7f** [comment]
After a specific firmware (or hardware) version (as described in https://github.com/AshleyF/briefcubing/blob/master/experimental/gan356i/gan.js), 356i encrypted its data. 
Right now, neither do I have a new 356i nor do any of my friends, so I cannot collect enough data to find the decryption algorithm.

**Comment by boogie** [comment]
Thanks for the answer. Do you think I can help you with collecting logs or specific responses? Or any other way?

**Comment by boogie** [comment]
I was able to find out the new Giiker encryption (and next day I've found an even better solution online), so I can say I have some experience about it.

**Comment by cs0x7f** [comment]
Awesome. If you find out how 356i encrypt their data, you can write a document to introduce it or implement your own web-bluetooth tools. (Someone else has told me 356i adopts AES256 to encrypt the data.

**Comment by boogie** [comment]
Okay, at the moment I have no idea how to start, so any ideas are welcomed (will check AES256).

**Comment by boogie** [comment]
@cs0x7f Can you connect me with the one told you AES256? I have doubts: does the cube powerful enough (memory, speed of the microcontroller) for this? Also AES256 works with 128 bit long chunks (16 bytes), and we have 18-19 bytes.

**Comment by HoshiYamazaki** [comment]
Just curious, because Gan company will never tell me because of marketing and moral policy etc.

Is there evidence that 356i Chinese version is different than EU/USA release? I don't know about physical changes, but I see you guys are talking about firmware. Are there different Gan 356i chipsets than only one?

**Comment by boogie** [comment]
We have evidence that the cubes released with earlier firmware has no encryption, and from firmware version 1.0.7 the cube is using an encrypted communication. Maybe it's just a coincident that EU/USA cubes have been released with new firmwares. I guess all new cubes will get a new firmware.

**Comment by cs0x7f** [comment]
> We have evidence that the cubes released with earlier firmware has no encryption, and from firmware version 1.0.7 the cube is using an encrypted communication. Maybe it's just a coincident that EU/USA cubes have been released with new firmwares. I guess all new cubes will get a new firmware.

The decryption algorithm has been successfully developed recently. So cstimer is able to decrypt the data and obtain the cube state right now. Even though, since the web bluetooth api is experimental, the lack of robustness is predictable.

**Comment by HoshiYamazaki** [comment]
> We have evidence that the cubes released with earlier firmware has no encryption, and from firmware version 1.0.7 the cube is using an encrypted communication. Maybe it's just a coincident that EU/USA cubes have been released with new firmwares. I guess all new cubes will get a new firmware.

Is there an way to upgrade firmware of cube?

**Comment by boogie** [comment]
@HoshiYamazaki I think there's no way. The official app never upgraded the firmware of my cube. Maybe the firmware is stored in a ROM, or a later version will implement the upgrade process.

**Comment by HoshiYamazaki** [comment]
> @HoshiYamazaki I think there's no way. The official app never upgraded the firmware of my cube. Maybe the firmware is stored in a ROM, or a later version will implement the upgrade process.

So possibility of firmware upgrade is unkown, and only Gan know if it's possible. I think it should be, since there could be encountered bugs that they could fix. But if this is hardware releated... who knows.
